### ISSUE TITLE
Spaces in user path in windows will make mklink call fail because of missing quotes

### ISSUE THREAD

**Issue by eduardograna** [AcademySoftwareFoundation/rez#1066]
Rez version: 2.84.0;
    Platform and operating system: windows-10.0.19041;
    Contextual information: Trying the quickstart guide;
    Simplest possible steps to reproduce: 1) have a user folder with spaces 2) run rez-bind python

Hello!
Just a silly comment.
While trying the quickstart guide, and running the 'rez-bind python'  I got an error because paths with spaces (my user directory in this case) should be between quotes in cmd call.
`
 File "c:\work\work\rezinstall\lib\site-packages\rez\utils\platform_.py", line 510, in symlink
    subprocess.check_output("mklink %s %s" % (link_name, source), shell=True)
  File "C:\WinPython27\python-2.7.13.amd64\Lib\subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'mklink c:\users\eduardo grana\packages\python\2.7.13\platform-windows\arch-AMD64\os-windows-10.0.19041\bin\python c:\winpython27\python-2.7.13.amd64\python.exe' returned non-zero exit status 1
`

To fix this one (not sure if this issue is also appearing in other places) you could change 

https://github.com/nerdvegas/rez/blob/2d63748d34169ec918f2623c697818f3696c8c26/src/rez/utils/platform_.py#L510

to 

`
            subprocess.check_output('mklink "%s" "%s"' % (link_name, source), shell=True)
`

Cheers!
Eduardo

**Comment by davidlatwe** [comment]
Just a heads up that `rez-bind` is going to be deprecated (the decision has been made quite a while but not mentioned in wiki nor README, see this [mail thread](https://groups.google.com/g/rez-config/c/R1iJ9iE8Txg/m/4CdBB1T1BQAJ)), so don't spend too much time on it. :P
