### ISSUE TITLE
[Windows] Missing dependencies on windows install

### ISSUE THREAD

**Issue by alx00x** [AcademySoftwareFoundation/rez#1121]
Rez Version: 2.91.0
Platform: win 10

I've never used rez on linux so unfortunately i cannot compare but it looks like a few dependencies are missing from the install:

**graphviz**

When trying to generate graph:
```
FileNotFoundError: [WinError 2] "dot" not found in path.
```
Installing graphviz (and making sure dot.exe is in PATH) fixes this issue.

**Qt.py and PySide/PyQt**

When running `rez gui`:
```
ModuleNotFoundError: No module named 'Qt'
```
The actual bindings are also missing.

**Comment by JeanChristopheMorinPerso** [comment]
Hey, this is not a bug. I'll go ahead and close this.
