### ISSUE TITLE
update commits in CI to use dco

### ISSUE THREAD

**Issue by nerdvegas** [AcademySoftwareFoundation/rez#1202]
DCO is an aswf requirement (see https://github.com/apps/dco). Before enforcing it though, we should update any commits happening withing the gh workflows with sign-off, otherwise they'll start failing when we install the dco app / migrate to aswf gh org.

**Comment by JeanChristopheMorinPerso** [comment]
Commits in CI were disabled some time ago. It would be preferable to avoid creating commits from CI for simplicity and security reasons.
