### ISSUE TITLE
move from master to main

### ISSUE THREAD

**Issue by nerdvegas** [AcademySoftwareFoundation/rez#1203]
Do this ahead of time as part of adhering to aswf inclusion policy.
Verify that doing so won't breaking existing PRs (hopefully gh remaps appropriately)

**Comment by maxnbk** [comment]
Notes to self on procedure:
1. pull latest master branch, push to main
2. after creating `main`, mark it a protected branch.
3. move default PR branch to main
4. adjust _this branches_ PR target to main if necessary.
5. merge.
6. after workflows run on main branch, verify badges are correct
7. verify that the release process still works
8. verify after release that docs+wiki and benchmark workflows run and are committed correctly
9. verify that all other PRs are/were retargeted to main, or perform that process manually if necessary.
10. create a separate issue for upgrading the sphinx process to py3.7, upgrade to sphinx 4+, and replace the `master_doc` conf.py attrib with `root_doc`
11. create a separate issue for removing mentions of rez-talk.slack.com

**Comment by JeanChristopheMorinPerso** [comment]
@maxnbk step 13: Update the default branch on RTD.

**Comment by JeanChristopheMorinPerso** [comment]
RTD updated.

**Comment by maxnbk** [comment]
step 11 irrelevant now due to doc restructuring. Other sub-issues created separately.
