### ISSUE TITLE
remove hardcoded references to nerdvegas gh project where possible

### ISSUE THREAD

**Issue by nerdvegas** [AcademySoftwareFoundation/rez#1205]
I'm unsure as to whether there are places left we can do this, but it's worth a look before migration to aswf gh org

**Comment by nerdvegas** [comment]
done in wiki

**Comment by nerdvegas** [comment]
I think this is done now, the remaining instances only make sense to do after aswf migration:
* issue/pull links in inline comments
* instances in README.md (such as badge links)

**Comment by maxnbk** [comment]
I've resolved every other nerdvegas repo reference, excluding rez-shotgun which is a legacy repo still residing at nerdvegas, and omitting personal author references in changelogs and so forth.
The only thing remaining is sonarlcloud for which a separate issue exists, so I believe this is closeable. please reopen if you believe there is something else, @nerdvegas .

**Comment by cuckon** [comment]
Sorry what happened? Any context?
