### ISSUE TITLE
add SUPPORT.md

### ISSUE THREAD

**Issue by nerdvegas** [AcademySoftwareFoundation/rez#1230]

**Comment by maxnbk** [comment]
It turns out that @jmertic has adjusted some of the verbiage which applies to this item. We no longer require a "SUPPORT.md", merely the existence of various information about how to receive support with the project. In essence, #1721 will complete this issue when closed.

**Comment by jmertic** [comment]
You could keep the file and just point to wherever these options are listed; that might help people discover support options.

**Comment by maxnbk** [comment]
Closed by #1721
