### ISSUE TITLE
establish Technical Steering Committee

### ISSUE THREAD

**Issue by nerdvegas** [AcademySoftwareFoundation/rez#1246]
Please comment on this issue if you're interested in becoming a member of the TSC. Being a member involves attending the TSC meetings (which I believe would be fortnightly), where we will discuss project development.

Please respond with:
* Your email address
* The employer you represent, if any.

I can then include you in further correspondence as we get the TSC up and going.

For more info, see https://tac.aswf.io/process/tsc_faq.html

Thx,
A

**Comment by maxnbk** [comment]
maxnbk@gmail.com .

**Comment by jasoncscott** [comment]
jason_scott@siggraph.org

**Comment by ColinKennedy** [comment]
@colinvfx@gmail.com

**Comment by instinct-vfx** [comment]
instinctvfx@googlemail.com

**Comment by rydrman** [comment]
ryan@bottriell.ca

**Comment by RoseAllenM** [comment]
RoseAllenM@gmail.com

**Comment by fnaum** [comment]
fede.naum@gmail.com

**Comment by JeanChristopheMorinPerso** [comment]
jean_christophe_morin@hotmail.com

**Comment by sirfuzzalot** [comment]
tomsaunders.code@gmail.com

**Comment by davidlatwe** [comment]
davidlatwe@gmail.com

**Comment by manuelkoester** [comment]
manuelkoestercg@gmail.com

**Comment by kimpressive** [comment]
kim.bourdette@gmail.com

**Comment by dekekincaid** [comment]
dekekincaid@gmail.com

**Comment by predat** [comment]
sylvain@predat.fr

**Comment by GreenEminence** [comment]
mwojt@platige.com
Platige Image S.A.
We're using Rez since the dawn of time.

**Comment by aka-anoop** [comment]
anoop@codecg.com
[Code CG](https://codecg.com)

**Comment by bpabel** [comment]
007brendan@gmail.com
Walt Disney Imagineering

**Comment by skral** [comment]
rez@sebastiankral.de
Pixomondo

**Comment by mstreatfield** [comment]
mstreatfield@gmail.com
Epic Games

**Comment by jeffbradley-dreamworks** [comment]
jeff.bradley@dreamworks.com
DreamWorks

**Comment by noemartinez-dwa** [comment]
noe.martinez@dreamworks.com
DreamWorks

**Comment by zachlewis** [comment]
zachcanbereached@gmail.com
Company 3 / Method

**Comment by nerdvegas** [comment]
Hello all,

Let's get the ball rolling on this. I've moved to a discussion, please take part: https://github.com/AcademySoftwareFoundation/rez/discussions/1353

**Comment by JeanChristopheMorinPerso** [comment]
Closing since the TSC has been formed 6 months ago.
