### ISSUE TITLE
rez executables aren't removed in windows install

### ISSUE THREAD

**Issue by nerdvegas** [AcademySoftwareFoundation/rez#1258]
As part of the install process, rez cli tools are copied into a /rez subdir within the venv bin path - this is so that other unrelated exes (such as python) aren't accidentally run from rez's venv. See https://github.com/nerdvegas/rez/blob/master/install.py#L86-L90.

The specs.keys() returns a list like ['rez', 'rezolve', '_rez-complete', '_rez_fwd', 'rez-bind', 'rez-build', ...], but on windows the files all have the ".exe" extension. Meaning the line if os.path.isfile(filepath): always returns False, and those files never get deleted.

**To Reproduce**
1. perform an install on windows

**Expected behavior**
rez cli tools in root bin dir are deleted

**Actual behavior**
rez cli tools in root bin dir are not deleted

**Related Issues/PRs**
* #1170

**Comment by instinct-vfx** [comment]
Good catch [hughetop](https://github.com/hughetop). That had never occured to me as i never really loooked into the non-rez folder. Will take a look.
