### ISSUE TITLE
rez-pip doesn't include arch/platform in variant for packages with platform-specific generated scripts

### ISSUE THREAD

**Issue by bpabel** [AcademySoftwareFoundation/rez#1286]
rez-pip currently only includes `platform` and `arch` in the variant when generating a rez package for python packages that aren't pure python. However, pure python packages that define entry points scripts (console_scripts or gui_scripts) will generate platform-specific executables, and require the platform and arch tags, so that installations from different platforms can be installed to separate variants, each with their own set of generated platform-specific executables.

**Environment**
* OS - all os's
* Rez version - "2.107.0")
* Rez python version - Python 3.7.7

**To Reproduce**
1. rez-pip a pure python package with console scripts (e.g. rez-pip -i flit)

**Expected behavior**
The generated package.py variant includes the platform and arch packages it was generated from.

**Actual behavior**
The generated package.py variant does not include the platform and arch packages it was generated from (only the python version).

**Comment by bpabel** [comment]
Just wanted to follow up on how to push this along. It's a critical show-stopping bug for `rez-pip`. There are some automated failures in the CI that look permission related but I'm not sure.

**Comment by nerdvegas** [comment]
I'll take a look this week.
Thx
A
