### ISSUE TITLE
REP-004: Documentation Improvements

### ISSUE THREAD

**Issue by ColinKennedy** [AcademySoftwareFoundation/rez#1292]
There's been a some discussions around Rez's documentation. Both in terms of ["what can we document better"](https://github.com/nerdvegas/rez/discussions/1277) as well as ["how can we improve what we have documented, already"](https://academysoftwarefdn.slack.com/archives/C0321B828FM/p1650437035544429)

GitHub Discussion: #1293 

This REP will focus on the latter portion. From group discussion, these key desires and improvements have been identified

- [ ] REP-004.1 - Versioned Sphinx documentation
    - [ ] The majority choice is to build + integrate Rez documentation using readthedocs.io
- [ ] REP-004.2 - Better / Fully automated Rez API documentation
- [ ] REP-004.3 - Unity between Rez's wiki pages and the Rez Sphinx documentation
    - [ ] Eventually deprecate GitHub Pages, following a separate audit once contributors are happy with the Sphinx results
- [ ] REP-004.4 - Documentation previews In PRs
- [ ] REP-004.5 - Ensure clean Sphinx builds

## REP-004.1 - Versioned Sphinx documentation

The desire is to have documentation per-Rez-version **as well as** a "latest" / "stable" location which is consistent with Rez's latest release. Leveraging readthedocs.io to handle this will be a key point of this work.

## REP-004.2 - Better / Fully automated Rez API documentation

Rez API documentation is currently out of date and manually generated. Use `autosummary`, `sphinx-apidoc`, or another, similar technology to make the API pages on the fly, so they're always kept up to date.

## REP-004.3 - Unity between Rez's wiki pages and the Rez Sphinx documentation

Rez Sphinx documentation and Rez GitHub pages (wiki markdown) are currently separate. Making them as a single source will encourage more people to make documentation as well as make the documentation more meaningful, because hand-written documentation will be able to directly link to API code and vice versa.

## REP-004.4 - Documentation Previews In PRs

Currently, hand-written documentation or API documentation changes which are still in PR must be reviewed locally in order to see the "rendered" result, which is not ideal. Assuming REP-004.1 is successfully implemented with readthedocs.io, we could leverage readthedocs.io's  PR documentation preview service. (See https://docs.readthedocs.io/en/stable/pull-requests.html for details)

## REP-004.5 - Ensure clean Sphinx builds
Requires: **REP-004.1**

Rez's Sphinx documentation currently builds with about 90 warnings and a few error. A general clean-up would be greatly appreciated. Also, once Sphinx is better supported, we'll be able to go back in and improve our use of Sphinx roles (`:ref:`, `:doc:`, `:mod:`, `:func:`, etc) as a separate, parallel effort.

**Comment by ColinKennedy** [comment]
Other points to potentially add as part of REP-004

- Changelog as part of documentation (example: https://ftrack-python-api.readthedocs.io/en/stable/release/release_notes.html)
- Markdown / ReST

Those points may need more discussion before we add them to the REP.

**Comment by JeanChristopheMorinPerso** [comment]
I created https://github.com/nerdvegas/rez/discussions/1293 to help with discussions. It should hopefully make it eaiser to have sub-threads.

**Comment by ColinKennedy** [comment]
Added a PR for REP-004.1 and REP-004.2 over at https://github.com/nerdvegas/rez/pull/1295
