### ISSUE TITLE
Add CLA PDFs to repo

### ISSUE THREAD

**Issue by nerdvegas** [AcademySoftwareFoundation/rez#1327]
Ala https://github.com/AcademySoftwareFoundation/OpenTimelineIO/blob/main/OTIO_CLA_Corporate.pdf

Link: https://contributor.easycla.lfx.linuxfoundation.org/#/cla/project/2129b6ab-57e6-4db9-9752-1e39e882fdfe/user/31845cd9-2f95-43f0-a8de-4a65863ba293?redirect=https:%2F%2Fgithub.com%2FAcademySoftwareFoundation%2Frez%2Fpull%2F1325

Currently waiting on permissions issue to be fixed.

**Comment by maxnbk** [comment]
We don't need to add the PDF's to the repo, only to link to them, which #1721 will address.
