### ISSUE TITLE
PyQt5 via rez-pip: ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by ColinKennedy** [AcademySoftwareFoundation/rez#1337]
PyQt5 version 5.15.7 fails to run even after installing it via Rez.

**Environment**
* OS: Windows 10
* Rez version: 2.110.0
* Rez python version (output of "rez-python --version"): 3.7.9

**To Reproduce**
- Install Python 3.7
```
C:\Users\my_user>where python
C:\Users\my_user\AppData\Local\Programs\Python\Python37\python.exe
```
- Install Rez using that python (`python install.py -v C:\Users\my_user\rez-2.110.0-python-3.7`)
- rez-bind python
```
C:\WINDOWS\system32>rez-bind python
searching c:\users\my_user\rez-2.111.0-python-3.7\lib\site-packages\rez\bind..
.
creating package 'python' in C:\Users\my_user\packages...
searching c:\users\my_user\rez-2.111.0-python-3.7\lib\site-packages\rez\bind...
creating package 'arch' in C:\Users\my_user\packages...
13:56:01 WARNING  Skipping installation: Package variant already exists: c:\users\my_user\packages\arch\AMD64\package.py[]
searching c:\users\my_user\rez-2.111.0-python-3.7\lib\site-packages\rez\bind...
creating package 'os' in C:\Users\my_user\packages...
13:56:01 WARNING  Skipping installation: Package variant already exists: c:\users\my_user\packages\os\windows-10.0.19041.SP0\package.py[]
searching c:\users\my_user\rez-2.111.0-python-3.7\lib\site-packages\rez\bind...
creating package 'platform' in C:\Users\my_user\packages...
13:56:01 WARNING  Skipping installation: Package variant already exists: c:\users\my_user\packages\platform\windows\package.py[]
The following packages were installed:

PACKAGE  URI
-------  ---
python   c:\users\my_user\packages\python\3.7.9\package.py
```

- Install PyQt5 as a Rez package, using rez-pip

```
C:\Users\my_user>rez-env PyQt5 python -- python -c "from PyQt5 import QtGui"
09:43:43 ERROR    PackageFamilyNotFoundError: package family not found: PyQt5 (searched: C:\Users\my_user\packages; C:\Users\my_user\releases)

C:\Users\my_user>rez-pip --install PyQt5 --python-version=3 --release
09:43:53 INFO     Trying to use pip from python package
09:43:53 INFO     Trying to use pip from pip package
09:43:53 WARNING  Found no pip in any python and/or pip rez packages!
09:43:53 WARNING  Falling back to pip installed in rez own virtualenv:
09:43:53 WARNING         pip: 20.1.1 (c:\users\my_user\rez-2.111.0-python-3.7\lib\site-packages\pip\__init__.py)
09:43:53 WARNING      python: 3.7.9 (c:\users\my_user\rez-2.111.0-python-3.7\scripts\python.exe)
09:43:53 INFO     Installing 'PyQt5' with pip taken from 'c:\\users\\my_user\\rez-2.111.0-python-3.7\\scripts\\python.exe'
Collecting PyQt5
  Downloading PyQt5-5.15.7-cp37-abi3-win_amd64.whl (6.8 MB)
     |████████████████████████████████| 6.8 MB 3.3 MB/s
Collecting PyQt5-Qt5>=5.15.0
  Downloading PyQt5_Qt5-5.15.2-py3-none-win_amd64.whl (50.1 MB)
     |████████████████████████████████| 50.1 MB 69 kB/s
Collecting PyQt5-sip<13,>=12.11
  Downloading PyQt5_sip-12.11.0-cp37-cp37m-win_amd64.whl (77 kB)
     |████████████████████████████████| 77 kB 3.1 MB/s
Installing collected packages: PyQt5-Qt5, PyQt5-sip, PyQt5
Successfully installed PyQt5-5.15.7 PyQt5-Qt5-5.15.2 PyQt5-sip-12.11.0
WARNING: You are using pip version 20.1.1; however, version 22.1.2 is available.

You should consider upgrading via the 'c:\users\my_user\rez-2.111.0-python-3.7\scripts\python.exe -m pip install --upgrade pip' command.
09:44:40 INFO     Installed [PyQt5-5.15.7] c:\users\my_user\releases\PyQt5\5.15.7\package.py (69fe24dc50b5aaf01d2aab48736b310ab772af5a)
09:44:53 INFO     Installed [PyQt5_Qt5-5.15.2] c:\users\my_user\releases\PyQt5_Qt5\5.15.2\package.py (69fe24dc50b5aaf01d2aab48736b310ab772af5a)
09:44:53 INFO     Installed [PyQt5_sip-12.11.0] c:\users\my_user\releases\PyQt5_sip\12.11.0\package.py (69fe24dc50b5aaf01d2aab48736b310ab772af5a)
09:44:53 INFO     3 packages were installed.
```

- Do a rez-env + call PyQt5
```
C:\Users\my_user>rez-env PyQt5 python -- python -c "from PyQt5 import QtGui"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: DLL load failed: The specified module could not be found.
```

**Expected behavior**
An import with no failures

**Actual behavior**
ImportError: DLL load failed: The specified module could not be found. is raised

**Extra Details**
I've reproduced this on two separate Windows machines. Oddly enough, re-doing the same steps with PySide2 works fine. Looking online, many users suggest that the issue is a missing system Python .dll or importing PyQt5 from a different python interpreter than the one was installed. However rez-bind symlinks to the system Python install and in the repro steps, we use the same Python throughout. The rez-pip uses "c:\\users\\my_user\\rez-2.111.0-python-3.7\\scripts\\python.exe" but even if you call `c:\\users\\my_user\\rez-2.111.0-python-3.7\\scripts\\python.exe -c "from PyQt5 import QtGui"` it still would fail with the same error.

It seems to be an issue with PyQt5 or my host machines but I'm not sure which is the likely cause. Any advice would be appreciated.

**Comment by instinct-vfx** [comment]
Could you do a resolve without command so you get the rez-context output and paste that here? (Not using PyQt for licensing reasons)

**Comment by ColinKennedy** [comment]
Are you asking for `rez-env -o` output? If so, this is it:

```
C:\Users\my_user>rez-env PyQt5 -o context.rxt

C:\Users\my_user>rez-context context.rxt
resolved by my_user@SelecaoOne, on Thu Jun 23 15:49:45 2022, using Rez v2.111.0

requested packages:
PyQt5
~platform==windows           (implicit)
~arch==AMD64                 (implicit)
~os==windows-10.0.19041.SP0  (implicit)

resolved packages:
PyQt5-5.15.7               c:\users\my_user\releases\PyQt5\5.15.7\69fe24dc50b5aaf01d2aab48736b310ab772af5a
PyQt5_Qt5-5.15.2           c:\users\my_user\releases\PyQt5_Qt5\5.15.2\69fe24dc50b5aaf01d2aab48736b310ab772af5a
PyQt5_sip-12.11.0          c:\users\my_user\releases\PyQt5_sip\12.11.0\69fe24dc50b5aaf01d2aab48736b310ab772af5a
arch-AMD64                 c:\users\my_user\packages\arch\AMD64 (local)
os-windows-10.0.19041.SP0  c:\users\my_user\packages\os\windows-10.0.19041.SP0 (local)
platform-windows           c:\users\my_user\packages\platform\windows (local)
python-3.7.9               c:\users\my_user\packages\python\3.7.9\platform-windows\arch-AMD64\os-windows-10.0.19041.SP0 (local)
```

**Comment by instinct-vfx** [comment]
Not sure if this is related. My Python Package does have the DLL in question and it is also on path. Reading the replies there is a bit disheartening. I sadly can not spend a lot of time on this currently, but i could reproduce it also with a python package not created with rez-bind. https://stackoverflow.com/questions/42863505/dll-load-failed-when-importing-pyqt5

The accepted reply is a bit of a let-down

**Comment by JeanChristopheMorinPerso** [comment]
You could use the [dumpbin](https://docs.microsoft.com/en-us/cpp/build/reference/dumpbin-command-line?view=msvc-170) utility on the `.pyd` to list the direct dependencies and make sure at least all direct dependencies exists and can be found by Python.

`dumpbin /DEPENDENTS <path to pyd>`.

>Oddly enough, re-doing the same steps with PySide2 works fine

Well, PyQt and PySide are two different beats. You can only compare them by their API. The way they are created and compiled and packaged is different.

**Comment by ColinKennedy** [comment]
I convinced the users to go with PySide so this issue is no longer a problem for us anymore. Will close this ticket. If others see this and would like help, we can re-open / re-visit.

**Comment by loonghao** [comment]
> I convinced the users to go with PySide so this issue is no longer a problem for us anymore. Will close this ticket. If others see this and would like help, we can re-open / re-visit.

Hi @ColinKennedy I deploying the latest version of PyQt5 through rez these days, and I found that the .dll file that PyQt5 depends on is not included in the .whl file in the version after PyQt5 `5.15.1`.
Install the 5.15.1 or 5.15.2 version, import PyQt5 will not have the problem of `.dll` missing

![image](https://user-images.githubusercontent.com/13111745/184048969-bd01481b-26a7-4119-937a-c261549423c3.png)

![image](https://user-images.githubusercontent.com/13111745/184049426-2f152056-1b80-47dd-8378-6dc0fb2dce58.png)
![image](https://user-images.githubusercontent.com/13111745/184049491-edf9cf0d-f189-4304-a1bd-243cc105b600.png)
