### ISSUE TITLE
remove embedded virtualenv

### ISSUE THREAD

**Issue by nerdvegas** [AcademySoftwareFoundation/rez#1349]
virtualenv is LGPL, it must be removed from the project.

This means that py<3.7 will now have a system requirement on virtualenv, but that's not so bad - practically all of 
py<3.7 is py2, which is much closer to actual deprecation in vfx now. We will abort with an error if virtualenv cannot
be imported in this case.

Note related ticket #1348 - not sure specifically what's going on here, but let's just fall back to virtualenv if venv cannot be
imported, that seems more robust.

**Related Issues/PRs**
* #1348

https://lfscanning.org/reports/aswf/rez-2022-06-10-b01cab7b-ff86-4d95-9353-3af77d08c868.html

**Comment by JeanChristopheMorinPerso** [comment]
What we could do is use the [zipapp](https://virtualenv.pypa.io/en/20.15.1/installation.html#via-zipapp) provided by virtualenv. We would just have to download it during install time.

**Comment by maxnbk** [comment]
Download at install time can be a dealbreaker for firewalled corps/studios.

**Comment by JeanChristopheMorinPerso** [comment]
We could add a flag to disable the virtualenv download.

**Comment by bpabel** [comment]
Looks like virtualenv uses an MIT license now -- https://github.com/pypa/virtualenv/blob/main/LICENSE
