### ISSUE TITLE
TSC Meeting 2022 2022-08-18

### ISSUE THREAD

**Issue by nerdvegas** [AcademySoftwareFoundation/rez#1362]
**Agenda**
* None (this is the first meeting, and is largely procedural)

**Comment by nerdvegas** [comment]
The idea with these issues is that people take part in this thread in order to determine the agenda for the upcoming meeting. Someone (secretary/chairperson) is responsible for updating the Agenda in the issue description, in response to discussion.

**Comment by maxnbk** [comment]
closed by https://github.com/AcademySoftwareFoundation/rez/pull/1365
