### ISSUE TITLE
TSC Meeting 2022 2022-09-15

### ISSUE THREAD

**Issue by nerdvegas** [AcademySoftwareFoundation/rez#1363]
**Agenda**
* Present/introduce TSC members
* Open Q&A
  * What are your pain points?
  * Where do you most want to see effort put into the project currently?
  * How do we add the most value (and drive further adoption) with the least effort?
* Discuss prioritization of efforts, eg:
  * ASWF matters (finalizing governance.md etc);
  * Identifying and triaging quality of life improvements / low hanging fruit;
  * Triaging long-standing PRs;
  * Planning/implementation of longer term features
* Discuss branch/release workflow
  * Current strategy is simple and linear, which has its downsides
  * Should we move to (eg) dev branch and scheduled major releases?

**Comment by maxnbk** [comment]
Possible agenda items to propagate from previous agenda:

* Discussion about any WIP (or lack of progress) updates towards governance.md/contributing.md/releasing.md files.
* Delegation or creation of github issues for action items determined from first TSC meeting.
* Follow-up discussion / status for first non-Allan release if resulting action items neccesary.

**Comment by JeanChristopheMorinPerso** [comment]
I would like to see TSC members come up with what they think is the most pressing issues.

For example n the last couple of months, we've received a lot of bug reports from our Windows users (see https://github.com/AcademySoftwareFoundation/rez/issues?q=is%3Aopen+is%3Aissue+label%3Atopic%3Awindows). There has been a lot of activity around `rez-test` too and it might be a good idea to see where we are at on that subject.

It would also be a good idea to go through the opened issues and PRs and triage them. Though I understand this will be a long process that can be done asynchronously by TSC members. On my side I usually try to triage as we get new issues reported, but I sometimes miss stuff.

**Comment by JeanChristopheMorinPerso** [comment]
I took the liberty to add a quick point to the agenda to present the TSC members to everybody that will join the meeting.

**Comment by instinct-vfx** [comment]
- Discuss how we want to manage/govern (or not do so) closely related side projects. The first, most prominent one likely being rez-pip. If we make it a separate project, where does the code live, who is in charge? Is this a "sub project" or a separate effort?

**Comment by maxnbk** [comment]
- Would like to discuss, on potentially a recurring basis, "using some of the slack channels common questions when new users are getting started/setup" as a reference point for "things that are not well-documented or explained or as a potential tutorial topic".
- Would also like to discuss / determine, early in the meeting, how we choose which of many agenda points will be the first agenda points in the queue, since we are likely to fall down rabbit-holes, and I don't want non-TSC attendees submitting their discussion points to feel slighted by TSC member talking points being prioritized, when they may have a limited schedule of meetings they can attend.

**Comment by JeanChristopheMorinPerso** [comment]
I'd move the Q&A before the "prioritization" work. My thinking is that the TSC meetings are there for the community and we should give them as much time as possible to interact with us. Getting feedback from the community will also help us better determine where we can focus our energy.

**Comment by nerdvegas** [comment]
Order changed.

Ok, I think we'll have enough to talk about and I wouldn't be surprised if we don't get to branch/release workflow at all (which would be fine). Yeah I think starting with the Q&A will be good, for a lot of people this may feel like the first time they've been able to voice this stuff, it'll help get people feeling involved.
