### ISSUE TITLE
Expose an environment flag if any locally installed packages were resolved in the current context

### ISSUE THREAD

**Issue by JoshkVFX** [AcademySoftwareFoundation/rez#1371]
Looking for an easy way to know if I'm in a "development" environment using an environment variable
The consensus on the slack was to evaluate common environment variables for the rez local install path but that feels like both double handling data the resolver probably already has and has the potential to miss uncommon packages

**Motivation**
Exposing this info as an environment variable makes it easy to know if you're in a local development environment and easy to feed that into logging/monitoring

**Comment by JoshkVFX** [comment]
More than happy to put in a PR myself on this one. Just wanted to get thoughts and opinions before I do

Let me know if I've done anything wrong or if I could do anything better!

**Comment by JeanChristopheMorinPerso** [comment]
Hi @JoshkVFX ! Creating an issue before creating a PR is indeed a good idea!

It would be interesting to hear more about your use case and also what kind of changes you would propose. `rez-env` does already a decent (IMO) job at displaying local packages if any are present in the resolved list of packages. So I'm wondering, it that not enough? Or are you trying to make it clearer in some contexts? Perhaps you have a rez wrapper and you want it to fail if there is a local package resolved? Or maybe something else?

Knowing a little bit more about the use case will help to know if adding an environment variable is the way to go or if we can do something else instead.

Thanks!

**Comment by JoshkVFX** [comment]
Hey Jean,

For sure!

I'm looking to have get a really quick boolean of 'does this rez-context contain local packages' and I was hoping I could get that without checking all the root paths of the resolved packages

The reason I want this boolean (doesn't need to be a boolean, could be a string or anything) is so I can use that to feed our APM integration. So that way I can easily tag metrics as being from a development environment

Rez-env does a great job at showing that visually when you first get into a context, but I'm hoping to get that value much later, when I'm in a DCC running a publish or some other task/application

I can definitely traverse the package roots and compare to the local install path myself, caching that value, but it feels like that would be a good thing for rez to provide

Let me know your thoughts

Thanks,
Josh

**Comment by JeanChristopheMorinPerso** [comment]
Thanks. I remember now from the slack conversation.

Would you need a per package "flag" or a global" flag? I personally don't think it would make sense for a global flag. I'd more see a per package thing, maybe a `REZ_USED_LOCAL_RESOLVE` (to match the already existing `REZ_USED_RESOLVE` and `REZ_USED_EPH_RESOLVE`). But I'd still be curious to know your opinion and also other's opinion.

**Comment by JoshkVFX** [comment]
That's a good question

For the APM system I'm currently using I'm only looking for a global one, but it definitely makes more sense to have it per package, so you could implement some smarts if needed

And for my current use case I could just say 'does `REZ_USED_LOCAL_RESOLVE` exist/is not empty'

**Comment by maxnbk** [comment]
It's interesting to note that "whether someone used `--no-local`" is stored in the rez context.rxt directly, but I'm not sure it has a dedicated variable, other than being in the various CLI flag storing variables. I think it could make sense to store the per-package info in the rxt, (since it will stored the resolved path of each package anyway), and a global env var, so that if you just need a quick check on "is anything local", you have a quick answer, but if you need the granular info, you have it available in the context for inspection the way you might inspect anything else that granular. Seems like a lot of environment pollution otherwise?

**Comment by JoshkVFX** [comment]
Yeah I think we're in agreement one global environment variable (I'm leaning toward the list of local packages in `REZ_USED_LOXAL_RESOLVE` that @JeanChristopheMorinPerso suggested) and we'll definitely be storing some kind of 'is_local' flag per-package in the context rxt

**Comment by nerdvegas** [comment]
Is not using the rez api a requirement?

The canonical way to do this would be something like:
```
local_pkgs_exist = any(x.is_local() for x in mycontext.resolved_packages)
```

**Comment by nerdvegas** [comment]
*
```
local_pkgs_exist = any(x.is_local() for x in
ResolvedContext.get_current().resolved_packages)
```

**Comment by JeanChristopheMorinPerso** [comment]
One problem I see with the rez API is that it's a Python only thing, and also some studios don't want to have rez as a dependency (like myself for example).

We already expose implicit and resolved packages as environment variables. It seems logical to me to expose the local packages resolved.

**Comment by JoshkVFX** [comment]
For my current need that would likely solve it, but like Jean has said I would like to be able to use that outside of the python api

**Comment by JoshkVFX** [comment]
Put in this PR #1378 that sets the environment variable `REZ_USED_LOCAL_RESOLVE` to the same style of string as `REZ_USED_EPH_RESOLVE`

Right now I'm just running a generator expression that checks is_local on the resolved_pkgs list. Let me know if you'd prefer I go through and handle it like the `resolved_ephemerals` is on the resolver
