### ISSUE TITLE
Documentation for package_filter config inaccurate

### ISSUE THREAD

**Issue by herronelou** [AcademySoftwareFoundation/rez#1372]
I was looking at the documentation for package_filter, accessible here:
https://github.com/AcademySoftwareFoundation/rez/blob/master/src/rez/rezconfig.py#L365
https://github.com/AcademySoftwareFoundation/rez/wiki/Configuring-Rez#package_filter

The docs make it look like we're in a YAML config rather than a python config.
While the YAML in the docs does translate pretty much 1:1 to the expected python types, it takes a bit of a mental effort to translate between the 2, and at first I got it wrong, trying to enter `glob('*.beta')` instead of the expected `'glob(*.beta)'`

Additionally, it would seem like there is no such thing as `requirement(foo-5+)`, and that the proper string is `range(foo-5+)`?

I can possibly update the docs myself and update the examples to the right format but as I've just pieced it together I might be missing some subtleties .

**Expected behavior**
Documentation examples should be usable right away.

**Actual behavior**
Documentation examples can't be used directly and require translating into python

**Comment by JeanChristopheMorinPerso** [comment]
Hi @herronelou, the list if available rules can be seen at https://github.com/AcademySoftwareFoundation/rez/blob/master/src/rez/package_filter.py#L338-L342. as you said `requirement` isn't valid.

Feel free to open a pull request to improve this part of the docs!

**Comment by JeanChristopheMorinPerso** [comment]
The documentation for this lives in https://github.com/AcademySoftwareFoundation/rez/blob/master/src/rez/rezconfig.py#L360-L405.

**Comment by herronelou** [comment]
I'll do a PR when I have a little bit of time. How about the wiki, that's not in the repo directly is it?

**Comment by maxnbk** [comment]
The wiki is generated from the repo: https://github.com/AcademySoftwareFoundation/rez/tree/master/wiki

**Comment by nerdvegas** [comment]
See
https://github.com/AcademySoftwareFoundation/rez/blob/master/CONTRIBUTING.md#contributing-to-rez,
it explains how to contribute wiki changes. Note that it could be clearer
though. We'll be reworking CONTRIBUTING quite soon, I'll be sure to address
that.
