### ISSUE TITLE
Should be possible to configure that a resolve blocks until caching completes (and use the cache for all items)

### ISSUE THREAD

**Issue by maxnbk** [AcademySoftwareFoundation/rez#1379]
Subject says most of it.

Ideally this would be implemented as a rezconfig flag, and perhaps rez-env or similar would have a flag to ignore the caching step if a user merely wishes to check the resolve. `--solve-only`?

I imagine that this sort of workflow would be a requirement of s3-bucket-style repositories anyway, so we ought to support this in general.

**Motivation**
Some users may wish to enforce usage of only cached packages, and simply wait for caching to complete.

**Comment by JeanChristopheMorinPerso** [comment]
Some context around package caching can be found in [REP-003](https://github.com/AcademySoftwareFoundation/rez/issues/680). REP-003 mentions having a blocking caching mode.
