### ISSUE TITLE
env.PATH.prepend is not pre-pending.

### ISSUE THREAD

**Issue by mrpurest** [AcademySoftwareFoundation/rez#1420]
Describe the bug here.

**Environment**
* OS                 :  centos7
* Rez version   :  2.112.0
* Rez python version :  Python 2.7.5

**To Reproduce**
with this in package:

def commands():
    env.PATH.prepend("{root}/ffmpeg")

rez release, then rez env ffmpeg (or whatever package)

env | grep PATH

**Expected behavior**
my new ffmpeg path should be the first path in PATH

**Actual behavior**
looks like its the first "rez" path added to PATH, but after all the already existing system paths.

**Comment by JeanChristopheMorinPerso** [comment]
Hello @mrpurest , Rez seems to behave as it should. This behavior can be changed I think. For example you can use [standard_system_paths](https://github.com/AcademySoftwareFoundation/rez/wiki/Configuring-Rez#standard_system_paths) to define the default `PATH`, or you can use [all_parent_variables](https://github.com/AcademySoftwareFoundation/rez/wiki/Configuring-Rez#all_parent_variables), [all_resetting_variables](https://github.com/AcademySoftwareFoundation/rez/wiki/Configuring-Rez#all_resetting_variables), etc.

I don't know this area of rez really well though, but hopefully the documentation will help you. If you still can't achieve wnat you want after trying at these settings, please let us know!

**Comment by mrpurest** [comment]
hmmm...
If this is the intended behaviour then its a bit odd.

If I cannot prepend to the PATH variable, then system software will always be used in preference to the rez deployed software.

I will try adding PATH to the "parent variables" list, but since PATH is treated differently to other variables already, It's not totally clear what this will change

**Comment by mrpurest** [comment]
Adding PATH to the parent_variables fixed this for me. Thanks for you help!
