### ISSUE TITLE
Error launching detached shell with centos7/xterm/mate-terminal

### ISSUE THREAD

**Issue by antonshack** [AcademySoftwareFoundation/rez#1421]
Hey peeps,

I'm having what I assume to be an error while trying to resolve an env with the `detached` flag in a terminal. No separate terminal is opened, but the `xterm` help shows up:

```
rez env python --detached
Usage:
  xterm [OPTION…]

Help Options:
  -h, --help                      Show help options
  --help-all                      Show all help options
  --help-terminal                 Show terminal options
  --help-window-options           Show per-window options
  --help-terminal-options         Show per-terminal options
  --help-gtk                      Show GTK+ Options
  --help-sm-client                Show session management options

Application Options:
  --disable-factory               Do not register with the activation nameserver, do not re-use an active terminal
  --load-config=FILE              Load a terminal configuration file
  --save-config=FILE              Save the terminal configuration to a file
  --display=DISPLAY               X display to use

MATE Terminal Emulator
```
---

### Specs

 - rez: 2.112.0  (also tried on `2.89.1` and `2.103.4` with same results)
 - OS: CentOS Linux release 7.7.1908 (Core)
 - LSB Version:	:core-4.1-amd64:core-4.1-noarch
 - Kernel: Linux 5.4.135-1.el7.elrepo.x86_64
 - xterm --version: MATE Terminal 1.16.3

### Repro steps:

```
rez env --detached
```

### Expected behavior

That a new terminal opens with the resolved env and no `xterm` help shows up.

### Actual behavior

No separate terminal is opened and the `xterm` help shows up.

**Comment by JeanChristopheMorinPerso** [comment]
Hey @antonshack ! Can you try these commands and tell us their output please?

1. `rez-env python -- cat '$(dirname $REZ_CONTEXT_FILE)'/rez-shell.sh` (replace any "sensitive" values with random characters).
2. `rez-env -- echo '$SHELL'`
3. `rez-env -- readlink '/proc/$$/exe'`
4. `rez-config terminal_emulator_command`

That will hopefully help us know a little bit more what's going on.

Thanks!

**Comment by antonshack** [comment]
Hey @JeanChristopheMorinPerso, thanks for your answer!

It appears this one is on our side.

`xterm` was just not installed, but sym-linked for some historical reasons to `mate-terminal`. Hence the confusion with the help options showing up stating xterm where in fact they were the one from mate-terminal.

Thank you for your time. The ticket can be closed.
