### ISSUE TITLE
TSC Meeting 2023-01-19

### ISSUE THREAD

**Issue by bpabel** [AcademySoftwareFoundation/rez#1432]
Please respond to this issue with items you would like to see added to the agenda.

Items from attendees of TSC Meetings are prioritized above others, though ad-hoc reprioritization and discussion will occur.

Current agenda below:

- Issue grooming
- Branch cleanup

**Comment by instinct-vfx** [comment]
We did not get to my point last time, which is that i would like to have some informal input on the plans for the `provides` feature. We all seem to long for it and it also seems to solve a lot of problems for the community.

And then we have the recurring items if time allows:
  * Open Q&A
      * What are your pain points?
      * Where do you most want to see effort put into the project currently?
      * How do we add the most value (and drive further adoption) with the least effort?
  * Discuss prioritization of efforts, eg:
      * ASWF matters (finalizing governance.md etc);
      * Identifying and triaging quality of life improvements / low hanging fruit;
      * Triaging long-standing PRs;
      * Planning/implementation of longer term features

**Comment by maxnbk** [comment]
Notes pushed
