### ISSUE TITLE
Remove old branches

### ISSUE THREAD

**Issue by bpabel** [AcademySoftwareFoundation/rez#1433]
The repository has a quite long list of branches that can be removed.

**Comment by bpabel** [comment]
@AcademySoftwareFoundation/rez-tsc Is everyone fine at least deleting merged branches?

**Comment by instinct-vfx** [comment]
That's a yes from me

**Comment by JeanChristopheMorinPerso** [comment]
Yes from me too. We actually already approved this in one of the first TSC meetings.

**Comment by bpabel** [comment]
Deleted all merged branches.  There's still a handful of @nerdvegas 's old branches that I left.
