### ISSUE TITLE
rez-pip package tar.gz install & {root}

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [AcademySoftwareFoundation/rez#1439]
I am developing a python library for in-house tools. I'm using python to build and then install via `rez-pip` (see `build.py` below). However, once installed the package `{root}` does not point to the correct location. 

Once installed via `rez-pip`, `{root}` is reported to be 
`c:\programdata\rez\packages\nymus\0.1.0\platform-windows\arch-AMD64\python-3.9.13`
which is incorrect, as the library is actually installed to 
`C:\ProgramData\rez\packages\nymus\0.1.0\e7b64aebe77c11047a71e73bebf05e90cbb6361d`

Consequently the library cannot be found, as the incorrect path is added to `{PYTHONPATH}`

<details> <summary>package.py & build.py</summary>

```python
# package..py

name = "nymus"
version = "0.1.0"
build_requires = ["python-3"]
build_command = "python {root}/build.py"
requires = ["python_dotenv", "pandas-1.5.3", "click-8.1.3"]
uuid = "d72bcf23-5a7b-4448-ab8d-b9a5a23973ed"

@early()
def variants():
    """Generate variant for current platform"""
    from rez.package_py_utils import expand_requires

    requires = ["platform-**", "arch-**", "python-**"]
    return [expand_requires(*requires)]

def commands():
    info("Root path {root}")
    env.PYTHONPATH.append('{root}/python')
    env.PATH.append('{root}/bin')
```

```python
# build.py 

import os
import sys
from pathlib import Path
from subprocess import run

from rez.exceptions import BuildError


if __name__ == "__main__":
    sourcePath = Path(os.environ["REZ_BUILD_SOURCE_PATH"])

    if os.environ["REZ_BUILD_INSTALL"] == "1":

        binPath = Path(os.environ["REZ_BUILD_SOURCE_PATH"]) / "bin"
        installPath = Path(os.environ["REZ_BUILD_INSTALL_PATH"])
        buildPath = Path(os.environ["REZ_BUILD_PATH"])

        if sys.platform == "win32":
            proc = run(
                args=[
                    "python",
                    "setup.py",
                    "egg_info",
                    "--egg-base",
                    buildPath,
                    "sdist",
                    "--dist-dir",
                    str(buildPath),
                ],
                cwd=sourcePath / "python_libraries",
            )
            if proc.returncode != 0:
                raise BuildError(str(proc))

            proc = run(
                args=[
                    "rez-pip",
                    "--install",
                    buildPath
                    / f"{os.environ['REZ_BUILD_PROJECT_NAME']}-{os.environ['REZ_BUILD_PROJECT_VERSION']}.tar.gz",
                ],
            )
            if proc.returncode != 0:
                raise BuildError(str(proc))
        else:
            raise NotImplementedError(sys.platform)

```
</details>

**Environment**
* Windows
* Rez version: 2.112.0
* Rez python version: 3.9.13

**To Reproduce**
Build and install any python library

**Expected behavior**
`{root}` should be set correctly.

**Actual behavior**
`{root}` does not point to the install location of the package.

**Comment by instinct-vfx** [comment]
Without diving into the details why it happens this seems to be a case of hashed variants attribute not being set in the package.py though used for creating the variant.

I am a bit confused by the setup as a whole though. In a rez-pip workflow i would not expect a package.py to be present. Just a setup.py, build to bdist_wheel and rez-pip it.

Could you share why you are setting up the workflow like this? And also if there is a specific reason not to build as a wheel instead?

**Comment by JeanChristopheMorinPerso** [comment]
I have the same comments/questions as @instinct-vfx. Additionally, I'm not convinced that `expand_requires` works. Also, why do you required the arch and platform in the variant? Shouldn't these be requirements of `pandas`? Or your package uses Cython or CPython API directly?

**Comment by Anti-Distinctlyminty** [comment]
> Without diving into the details why it happens this seems to be a case of hashed variants attribute not being set in the package.py though used for creating the variant.
> 
> I am a bit confused by the setup as a whole though. In a rez-pip workflow i would not expect a package.py to be present. Just a setup.py, build to bdist_wheel and rez-pip it.

You're right, this the `rez-build` was then calling `rez-pip` which was daft. Obviously so, now that you pointed it out. 
Unless there's a good way to wrap this all up in a single build call, I'll have to build the tar.gz and then rez-pip install it.

> Could you share why you are setting up the workflow like this? And also if there is a specific reason not to build as a wheel instead?

Just that my experience is entirely with using setuptools in this way. If building as a wheel is the way to go, I'll look into it.

**Comment by Anti-Distinctlyminty** [comment]
> Also, why do you required the arch and platform in the variant? Shouldn't these be requirements of `pandas`? Or your package uses Cython or CPython API directly?

This was purely to circumvent this error:

```ERROR    ResourceError: Attempting to install a package without variants (MemoryVariantResource({'location': 'memory{0x1d9b9fd5cc0}', 'name': 'nymus', 'version': '0.1.0', 'index': None, 'repository_type': 'memory'})) into an existing package with variants (FileSystemPackageResource({'location': 'c:\\programdata\\rez\\packages', 'name': 'nymus', 'version': '0.1.0', 'repository_type': 'filesystem'}))```
