### ISSUE TITLE
Rez pip support for: pip_package>=x.y.* (syntax)

### ISSUE THREAD

**Issue by Louiszeifer** [AcademySoftwareFoundation/rez#1441]
Rez pip does not allow package requirements like pip_package>=1.9.* and fails with 

```
ValueError: '.*' not allowed for '>=' constraints
```
Would it be possible to allow this?

**Motivation**
We are hitting this issue more often and are required to wait until the maintainer removes
this syntax for the package requirement in newer versions. 
This makes it more cumbersome to install external packages.

e.g..:
rez pip -ir torchsde
https://github.com/google-research/torchsde

pip -ir pytorch_lightning==1.7.7
https://www.pytorchlightning.ai/

The latest version of pytorch_lightning (1.9.0) is working. But pytorch_lightning==1.7.7 is a requirement for second tool
we are trying to install. We cannot run the second tool in rez until the developer switch to a newer version of pytorch_lightning.

**Comment by JeanChristopheMorinPerso** [comment]
Hi @Louiszeifer , thanks for taking time to open this issue. If my memory serves me well, this syntax is not compliant with https://peps.python.org/pep-0440/. And [the library](https://github.com/pypa/packaging) we use to parse versions that come from packages stored on PyPI stopped supporting that syntax not so long ago. See https://github.com/pypa/packaging/issues/645 for example and https://discuss.python.org/t/should-we-permit-with-more-comparision-operators-in-version-specifiers.

The general consensus is it's an invalid syntax that was once permitted and is no more permitted and nobody seems to be in favor of bringing it back.

**Comment by Louiszeifer** [comment]
Thank you for pointing me in the right direction.
