### ISSUE TITLE
rez pip install error

### ISSUE THREAD

**Issue by wandth** [AcademySoftwareFoundation/rez#1455]
I want to install a pypi package as rez package by rez-pip
![image](https://user-images.githubusercontent.com/34237282/222372955-c927c634-ca40-4cc4-9bde-99a77b85f763.png)

```python
ModuleNotFoundError: No module named 'rez.vendor.enum.enum'; 'rez.vendor.enum' is not a package
```

**Environment**
* Rez version :2.112.0
* Rez python version : 3.9.11

**Comment by JeanChristopheMorinPerso** [comment]
Hi @wandth , how did you install rez? I saw in a previous issue that you were using bleeding-rez... Is it possible you moved from bleeding-rez to rez and your install is "corrupted"?

**Comment by wandth** [comment]
@JeanChristopheMorinPerso when i use pip rez, i reinstall the rez, so that is no rez package in my rez package path. i found it is python version conflict, i will submit i pr to repair the issue,, thanks
