### ISSUE TITLE
Remove/replace usage of PEP-0594 deprecated stdlib python modules

### ISSUE THREAD

**Issue by maxnbk** [AcademySoftwareFoundation/rez#1463]
I doubt we have much more than pipes in use from this, but good to address as in-advance as we can reasonably. python-3.13 is quite a bit of runway for us to address this.

https://peps.python.org/pep-0594/

**Comment by herronelou** [comment]
Found usage:

(ignoring usage found in vendored libraries)

`cgi`
https://github.com/AcademySoftwareFoundation/rez/blob/master/src/rezgui/widgets/ChangelogEdit.py#L6

`pipes`  (all usage is pipes.quote)

https://github.com/AcademySoftwareFoundation/rez/blob/6ea5b67a6017db4b9fc287e09668782b8f358cfb/src/rez/utils/elf.py#L9
https://github.com/AcademySoftwareFoundation/rez/blob/6ea5b67a6017db4b9fc287e09668782b8f358cfb/src/rez/pip.py#L26
https://github.com/AcademySoftwareFoundation/rez/blob/6ea5b67a6017db4b9fc287e09668782b8f358cfb/src/rezplugins/shell/csh.py#L8
https://github.com/AcademySoftwareFoundation/rez/blob/6ea5b67a6017db4b9fc287e09668782b8f358cfb/src/rez/shells.py#L20
https://github.com/AcademySoftwareFoundation/rez/blob/6ea5b67a6017db4b9fc287e09668782b8f358cfb/src/rezplugins/shell/sh.py#L10
https://github.com/AcademySoftwareFoundation/rez/blob/6ea5b67a6017db4b9fc287e09668782b8f358cfb/src/rez/build_process.py#L19
https://github.com/AcademySoftwareFoundation/rez/blob/6ea5b67a6017db4b9fc287e09668782b8f358cfb/release-rez.py#L14
https://github.com/AcademySoftwareFoundation/rez/blob/6ea5b67a6017db4b9fc287e09668782b8f358cfb/src/rezplugins/shell/tcsh.py#L13
https://github.com/AcademySoftwareFoundation/rez/blob/6ea5b67a6017db4b9fc287e09668782b8f358cfb/src/rez/bind/_utils.py#L16
https://github.com/AcademySoftwareFoundation/rez/blob/6ea5b67a6017db4b9fc287e09668782b8f358cfb/src/rez/release_vcs.py#L11
https://github.com/AcademySoftwareFoundation/rez/blob/6ea5b67a6017db4b9fc287e09668782b8f358cfb/src/rezplugins/build_system/custom.py#L13
https://github.com/AcademySoftwareFoundation/rez/blob/6ea5b67a6017db4b9fc287e09668782b8f358cfb/src/rez/package_test.py#L14

**Comment by herronelou** [comment]
I could do the update for these if we agree on the approach:

### Option 1: Keep it backward compatible:


Use:
```
try:
    from html import escape
except ImportError:
    from cgi import escape
```
and 
```
try:
    from shlex import quote
except ImportError:
    from pipes import quote
```

### Option 2: Python 3.3+ only

Import from new locations only:
```
from html import escape
from shlex import quote
```

**Comment by JeanChristopheMorinPerso** [comment]
I would go with option 2.

**Comment by JeanChristopheMorinPerso** [comment]
I created https://github.com/AcademySoftwareFoundation/rez/pull/1572
