### ISSUE TITLE
Shared code include decorator always returns None

### ISSUE THREAD

**Issue by SamuelWarner** [AcademySoftwareFoundation/rez#1471]
I've setup a simple test package. It uses a commands() function that is decorated with @include('utils') exactly like the documentation for shared code. However it is defining "utils" as None in every situation so I can't run functions from it. I tried making utils a method, removing variants, manually creating the .rez/include folder and putting the file in there, nothing works. It always returns None for the imported file.

**Environment**
* OS Windows 10.0.19041.SP0
* Rez version v2.112.0
* Rez python version  Python 3.7.4

**To Reproduce**
1. Create a package with a single variant and use the include decorator:
```
variants = [
    ['platform-windows']
]

@include('utils')
def commands():
    print(this.config.package_definition_python_path)
    print(utils)
    utils.fun_test()
```
2. Change `package_definition_python_path` to point to `C:\\Users\\swarner\\Desktop\\TestFolder` 
3. Put a single file in TestFolder directory called `utils.py` that has contents:
```
def fun_test():
    print("Inside fun test")
```
4. Run rez-env your_package

**Expected behavior**
I would expect rez to run and call the function "fun_test" after copying the utils.py file to the .rez/include directory in the package as per the docs. The console output would look something like:
```
C:\Users\swarner>rez-env test_package
C:\Users\swarner\Desktop\TestFolder
<module 'utils' from 'C:\path\to\package\include\copy\of\file'>>
Inside fun test

You are now in a rez-configured environment.

resolved by swarner@dev-machine, on Tue Apr 11 14:27:07 2023, using Rez v2.112.0

requested packages:
test_package
~platform==windows           (implicit)
~arch==AMD64                 (implicit)
~os==windows-10.0.19041.SP0  (implicit)

resolved packages:
test_package-1.0.0  c:\users\swarner\packages\test_package\1.0.0\platform-windows     (local)
platform-windows   r:\pipeline\configs\rez_package_repository\msc\platform\windows
```

**Actual behavior**
Instead I get "None" for the util variable and thus an error when trying to call the method inside. This is what I get as output: 
```
C:\Users\swarner>rez-env test_package
C:\Users\swarner\Desktop\TestFolder
None
14:30:33 ERROR    PackageCommandError: Error in commands in package 'c:\\users\\swarner\\packages\\test_package\\1.0.0\\package.py[0]':
'NoneType' object has no attribute 'fun_test'
```
In fact I get None across the board even if I try to include('nonExistantFile') which is odd because I would have thought that would raise an InvalidPackageError.

**Comment by SamuelWarner** [comment]
Ah, looks like it was the build step I was missing. Would be nice to have a way to share code that didn't require a rebuild of all the packages using it when it is updated but we can work with this. Thanks for taking the time to review and help me out!!

**Comment by SitiSchu** [comment]
Depending on what you want to do, if you can expose it as CLI application you could create a regular rez package and then inside your utils.py use `ResolvedContext` to resolve it and run it in a subprocess. This way you don't need to rebuild all packages every time you change something

**Comment by JeanChristopheMorinPerso** [comment]
>Would be nice to have a way to share code that didn't require a rebuild of all the packages using it when it is updated but we can work with this.

This would go against the ideology of rez. Released packages are immutable and that's why `@include` copies the mofule into the released package.
