### ISSUE TITLE
rez search COMMAND and glob takes relative file as argument

### ISSUE THREAD

**Issue by marco-ff** [AcademySoftwareFoundation/rez#1472]
If I have file(s) in the current path that match the search glob command I am seeing errors. I can workaround the issue by quoting the " " the glob command. I.e. this will error `rez search -t family ftrack*` but this will work `rez search -t family "ftrack*"`

**Environment**
* OS : CentOS 7.9
* Rez version: 2.112.0
* Rez python version (output of "rez-python --version") 2.7.5

**To Reproduce**
1. Terminal to a specific path. i.e. `$HOME`
2. touch a file called` ftrack-01.pub`
3. touch a file called `ftrack-01`
4. run: `rez search -v --nl -t family ftrack*`

Steps 2 - 4 have to happen while staying on the same path.

**Expected behaviour**
List all the families starting with ftrack, i.e.:
```
ftrack_api
ftrack_cinesyncplay
ftrack_connect
ftrack_connect_foundry
...
```

**Actual behaviour**
I  am seeing the following error message:
```
$ rez search -v --nl -t family ftrack*
usage: rez [-h] [-i] [-V] [-v] COMMAND ...
rez: error: unrecognized arguments: ftrack-01.pub
```
Interestingly, if only of the above files is present, i.e only ftrack-01 or ftrack-01.pub then I don't get an error but instead, I get a "wrong" no results message.

`No matching family found.
`
As mentioned initially, the issue can be avoided by quoting the glob:

`$ rez search -v --nl -t family "ftrack*"`

**Comment by JeanChristopheMorinPerso** [comment]
Hi @marco-ff. There is not much we can do unfortunately. `*` is automatically expanded by the shell, before the rez-search process is even started. See https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html.

> Bash scans each word for the characters ‘*’, ‘?’, and ‘[’. If one of these characters appears, and is not quoted, then the word is regarded as a pattern, and replaced with an alphabetically sorted list of filenames matching the pattern (see [Pattern Matching](https://www.gnu.org/software/bash/manual/html_node/Pattern-Matching.html)).

**Comment by marco-ff** [comment]
Thank you for the clarification Jean Christophe, of course, that makes total sense now.
I've probably only ever dealt with glob in the terminal in relation to file commands so the escape wasn't totally obvious at first. Perhaps we can just add a small note to the help for new users? Something like this perhaps:

```
positional arguments:
  PKG                   packages to search, glob-style patterns are supported
```

```
positional arguments:
PKG                     packages to search; use quotes around glob-style patterns (e.g., "mypkg*") to ensure proper interpretation
```
