### ISSUE TITLE
Culling of Python pkg cache files

### ISSUE THREAD

**Issue by dominiquekwiek** [AcademySoftwareFoundation/rez#1489]
I am having issues with my Python package cache being culled randomly despite being in use.  I know that there is the `package_cache_max_variant_days` (which we have not overriden) but the package is actively being used when it is being culled. 
  This issue surfaces as the Python package cache stopping working correctly:

```
[08:34:25][dkwiek] ~ $> rez-env python-3 -- python3
Fatal Python error: initfsencoding: Unable to get the locale encoding
LookupError: no codec search functions registered: can't find encoding

Current thread 0x00007fed486d7740 (most recent call first):
/tmp/rez_context_7xtwlxmu/context.sh: line 77: 23049 Aborted                 (core dumped) python3 "$@"
```

Inspecting the package cache it looks like most of the files in the Python install have been removed leaving only the `bin` directory remaining and the `.pyc` files.  e.g.

```
[08:50:15][dkwiek] /tmp/netfx/rez/cache $> tree rez-pkg-cache.old1/python/3.7.7/c2b8/a
rez-pkg-cache.old1/python/3.7.7/c2b8/a
├── bin
│   ├── 2to3
│   ├── 2to3-3.7
│   ├── easy_install-3.7
│   ├── idle3
│   ├── idle3.7
│   ├── pip
│   ├── pip3
│   ├── pip3.10
│   ├── pip3.7
│   ├── pydoc3
│   ├── pydoc3.7
│   ├── python3
│   ├── python3.7
│   ├── python3.7-config
│   ├── python3.7m
│   ├── python3.7m-config
│   ├── python3-config
│   ├── pyvenv
│   └── pyvenv-3.7
├── cmake
├── include
│   └── python3.7m
│       └── internal
├── lib
│   ├── pkgconfig
│   └── python3.7
│       ├── asyncio
│       │   └── __pycache__
│       │       ├── base_events.cpython-37.pyc
│       │       ├── base_futures.cpython-37.pyc
│       │       ├── base_subprocess.cpython-37.pyc
│       │       ├── base_tasks.cpython-37.pyc
│       │       ├── constants.cpython-37.pyc
...
365 directories, 251 files
```

Removing the bad package cache and regenerating correctly caches the files again:

```
rez-pkg-cache/python/3.7.7/c2b8/a
├── bin
│   ├── 2to3
│   ├── 2to3-3.7
│   ├── easy_install-3.7
│   ├── idle3
│   ├── idle3.7
│   ├── pip
│   ├── pip3
│   ├── pip3.10
│   ├── pip3.7
│   ├── pydoc3
│   ├── pydoc3.7
│   ├── python3
│   ├── python3.7
│   ├── python3.7-config
│   ├── python3.7m
│   ├── python3.7m-config
│   ├── python3-config
│   ├── pyvenv
│   └── pyvenv-3.7
├── build.rxt
├── cmake
│   └── FindPython.cmake
├── include
│   └── python3.7m
│       ├── abstract.h
│       ├── accu.h
│       ├── asdl.h
│       ├── ast.h
│       ├── bitset.h
│       ├── bltinmodule.h
│       ├── boolobject.h
│       ├── bytearrayobject.h
│       ├── bytes_methods.h
│       ├── bytesobject.h
│       ├── cellobject.h
│       ├── ceval.h
│       ├── classobject.h
│       ├── codecs.h
│...

365 directories, 8208 files
```

I have looked in the package cache logs but there are no references to the Python package cache being cleaned up and it is bizarre as the whole package version directory is not being culled.  Any help much appreciated!

**Comment by JeanChristopheMorinPerso** [comment]
Is it possible that there is a cron job running on your computer that deletes stuff in `/tmp` when it gets too full?

**Comment by dominiquekwiek** [comment]
Turns out this was `systemd-tmpfiles` culling our files (see https://www.thegeekdiary.com/centos-rhel-67-why-the-files-in-tmp-directory-gets-deleted-periodically/amp/).  Fix was to move to a non `/tmp` directory.

**Comment by JeanChristopheMorinPerso** [comment]
Moving stuff outside of `/tmp` was the next thing I was gonna suggest, but I was waiting on your answer :)

`/tmp` is generally very volatile by nature. For example stuff in `/tmp` won't survive a reboot.
