### ISSUE TITLE
Rez not finding a package created while it is running

### ISSUE THREAD

**Issue by romainaugier** [AcademySoftwareFoundation/rez#1490]
Hello,

I've made a software launcher at out studio that uses rez to manage environments and packages, and when a new package is released, Rez cannot find it, we have to restart our launcher for Rez to find it (so restart the python interpreter). I imagine Rez uses some sort of caching, though I have disabled it with `caching=False`, maybe there is something else to do.

**Environment**
* Windows 10
* Rez version : v2.112.0
* Rez python version : 3.10.5

**To Reproduce**
Code that faults : 
```py
from rez import ResolvedContext

...

rezContext = resolved_context.ResolvedContext(packagesRequest,
                                              caching=False,
                                              package_paths=[config.RELEASE_PACKAGES_PATH],
                                              package_caching=False)
```

**Expected behavior**
I expect it to find the package

**Comment by JeanChristopheMorinPerso** [comment]
Hello @romainaugier , that's a known behavior, see https://github.com/AcademySoftwareFoundation/rez/issues/1033 and https://github.com/AcademySoftwareFoundation/rez/issues/1043.
