### ISSUE TITLE
Take ownership of https://rez.readthedocs.io

### ISSUE THREAD

**Issue by JeanChristopheMorinPerso** [AcademySoftwareFoundation/rez#1517]
It was brought to our attention that https://rez.readthedocs.io exists and is basically the rez API docs from an old version. After some investigation, it turns out that it was generated and is owned by @mstreatfield.

We are currently in contact with him. This issue is simply to track our progress.

- [x] Rename to `rez` (the previous name was `Rez`).
- [x] Change repository URL to ASWF repo.
- [x] Change main branch to `master`.
- [x] Trigger a build and make sure it passes.
- [x] Verify that https://rez.readthedocs.io/en/latest/ is properly updated.

**Comment by JeanChristopheMorinPerso** [comment]
Me and @maxnbk received an invite. I updated the description to add a list of tasks. All tasks are done.

**Comment by maxnbk** [comment]
Marking closed. Reopen if there's any other tasks.
