### ISSUE TITLE
TSC chair transition after Allan stepped down

### ISSUE THREAD

**Issue by JeanChristopheMorinPerso** [AcademySoftwareFoundation/rez#1519]
This issue tracks what we need to do to cleanly transition after Allan stepped down.

- [x] Update PCC (Remove Allan from TSC and add chair role to @JeanChristopheMorinPerso and @maxnbk).
- [x] Update [GOVERNANCE.md](https://github.com/AcademySoftwareFoundation/rez/blob/master/GOVERNANCE.md).
  * https://github.com/AcademySoftwareFoundation/rez/pull/1518
- [x] Remove Allan from [CODEOWNERS](https://github.com/AcademySoftwareFoundation/rez/blob/master/CODEOWNERS).
  * https://github.com/AcademySoftwareFoundation/rez/pull/1511
- [x] Update GitHub permissions (Remove Allan from all rez related GitHub teams and remote him as owner).
  * https://jira.linuxfoundation.org/plugins/servlet/desk/portal/2/IT-25870
- [x] Update Allan's role on the [rez-discussion](https://lists.aswf.io/g/rez-discussion) and [rez-tsc-private](https://lists.aswf.io/g/rez-tsc-private) mailing lists.
  * https://jira.linuxfoundation.org/plugins/servlet/desk/portal/2/IT-25872
- [x] Gain access to the PyPI project (https://pypi.org/project/rez/) and remove Allan from list of maintainers.
- [x] Take ownership of https://groups.google.com/g/rez-config.

**Comment by JeanChristopheMorinPerso** [comment]
Alright, I think are are now done with the transition. If more actions need to be taken, please add them to the list ni the description and re-open the issue.

**Comment by JeanChristopheMorinPerso** [comment]
Re-opening. I realized that we don't have access to https://pypi.org/project/rez/.

**Comment by JeanChristopheMorinPerso** [comment]
@maxnbk and myself were added as owners of https://pypi.org/project/rez/. We have also remove dAllan from the PyPI project. So marking as done.

**Comment by JeanChristopheMorinPerso** [comment]
Re-opening because we forgot to ask Allan to transfer us https://groups.google.com/g/rez-config.

**Comment by jmertic** [comment]
Closing the loop - I've added documentation for future times this comes up at https://github.com/AcademySoftwareFoundation/tac/pull/455

**Comment by JeanChristopheMorinPerso** [comment]
Myself and @maxnbk are now owner of the mailing list. Stephen will work with the ASWF to see how we can make it read only and cleanly transition everybody from the google group to the ASWF mailing list (https://lists.aswf.io/g/rez-discussion).
