### ISSUE TITLE
Indirect Cycle Causes Conflict Graph to Hang Indefinitely

### ISSUE THREAD

**Issue by Pantsworth** [AcademySoftwareFoundation/rez#1568]
In certain cases, indirect cycles created with a `!` dependency can cause rez to hang indefinitely while trying to construct a fail graph. 

**Environment**
* macOS 13.5.2
* Rez: 2.111.3
* Python 3.9

**To Reproduce**
Attached is a zip file that contains 3 packages that should reproduce the issue. 

Download: [graph_repro.zip](https://github.com/AcademySoftwareFoundation/rez/files/13254812/graph_repro.zip)
```
unzip graph_repro.zip
export REZ_PACKAGES_PATH=graph_repro
rez-env foo-1 bar
```

**Expected behavior**
Expected behavior is a failure graph and text like so --
```
The context failed to resolve:
A package was completely reduced: (bar-0.0.1[] (dep(!foo-1.0.0) <--!--> foo==1.0.0))

Resolve paths starting from initial requests to conflict:
  foo-1 --> foo-1.0.0 --> bar-0.0.1 --> !foo-1.0.0
  bar --> bar-0.0.1 --> !foo-1.0.0
```

![foo_bar_graph_error](https://github.com/AcademySoftwareFoundation/rez/assets/7198619/51d4dfc4-0cb1-4c03-bf0f-2ce95d84c19e)

**Actual behavior**
Rez hangs forever after showing
```
The context failed to resolve:
A package was completely reduced: (bar-0.0.1[] (dep(!foo-1.0.0) <--!--> foo==1.0.0))
<no further output>
```

**Related Issues/PRs**
Happy to open a PR for this one - what's been working for us so far is changing the following lines to check if the node is already in `visited`. 
https://github.com/AcademySoftwareFoundation/rez/blob/371644d19de24d720cc0a4b14f6c17eeb61c55e1/src/rez/utils/resolve_graph.py#L56

https://github.com/AcademySoftwareFoundation/rez/blob/371644d19de24d720cc0a4b14f6c17eeb61c55e1/src/rez/utils/resolve_graph.py#L86

Original - 
```
            down = next((ne for ne in graph.node_neighbors[node]), None)
```

Patch - 
```
            down = next((ne for ne in graph.node_neighbors[node] if ne not in visited), None)
```

**Comment by JeanChristopheMorinPerso** [comment]
Thanks for reporting this @Pantsworth! Also, nice work on creating a small repro scenario!

If you think you know how to fix the problem, we'll definitely welcome a PR.

I'm curious, how often do you hit this bug?

**Comment by Pantsworth** [comment]
Thanks for the quick reply! 

There's really just one specific case where we're seeing it, which is how we set up python and openssl. 

In our setup, `python` requires `openssl`, but our most recent `openssl` package has `!python-2` and `!python-3.7` requirements, which was a workaround to keep our older python packages from resolving a too-new version of openssl, since they weren't pinned to a specific openssl version. Basically, python is `foo` in my example, and openssl is `bar`. 

Those package requirements by themselves don't cause any issues with resolving, but if there's a conflict somewhere else during the process, Rez can get stuck trying to draw/print the resolve graph due to the cycle in openssl/python. 

The fix I mentioned above should solve the issue - I think it's just the graphing step that's causing trouble here :)

**Comment by JeanChristopheMorinPerso** [comment]
Thanks for the additional information! It's always nice to hear how our users use rez and and define their dependencies.

Like I said, feel free to create a PR. Bonus points if you also add a test!
