### ISSUE TITLE
Show inheritance in Python API docs

### ISSUE THREAD

**Issue by brycegbrazen** [AcademySoftwareFoundation/rez#1574]
We'd like to show class inheritance in our Python API docs.

**Motivation**
To help ease navigation and increase clarity. 

A specific use case comes from the `rez.resolved_context` module, where the `package_filter` parameter expects a type of `PackageFilterBase`, but doing a search in the documentation of `PackageFilterBase` returns no useful results.

I would imagine that the docs could show parent classes if they exist, and perhaps a way to provide a hyperlink to the parent class in the documentation if applicable, or an inheritance diagram.

This may be as simple as changing a simple config option for the whole repo, a brief discussion of this issue started in [this Slack thread](https://academysoftwarefdn.slack.com/archives/C0321B828FM/p1699482755819869).

**Comment by JeanChristopheMorinPerso** [comment]
FYI, PackageFilterBase can be found here: https://github.com/AcademySoftwareFoundation/rez/blob/371644d19de24d720cc0a4b14f6c17eeb61c55e1/src/rez/package_filter.py#L19

**Comment by JeanChristopheMorinPerso** [comment]
@brycegbrazen I added the inheritance information in https://rez--1580.org.readthedocs.build/en/1580/. Let me know what you think.

**Comment by brycegbrazen** [comment]
@JeanChristopheMorinPerso Great improvement thank you! I noticed the actual PackageFilterBase class shows up in the Python API docs now too, so double whammy 👍

**Comment by JeanChristopheMorinPerso** [comment]
Indeed the base class now appears in the docs. There is also a lot more stuff exposed.

**Comment by JeanChristopheMorinPerso** [comment]
@brycegbrazen the docs should now have inheritance information.
