### ISSUE TITLE
Replace usages of `rez.vendor.enum` with the built-in enum module

### ISSUE THREAD

**Issue by JeanChristopheMorinPerso** [AcademySoftwareFoundation/rez#1648]
Now that we dropped support for Python 2, we can now use the built-in [enum](https://docs.python.org/3/library/enum.html) module.

Note that this doesn't apply to things inside `rez.vendor`. But if `rez.vendor.enum` is not used inside `rez.vendor`, we should remove `rez.vendor.enum` entirely.

**Comment by predat** [comment]
Hi @JeanChristopheMorinPerso,
for me, I don't see any good reason to keep rez.vendor.enum even for pika; I would drop it completely.
