### ISSUE TITLE
Rez auto delete rxt temp files make subprocess  rez-context faild.

### ISSUE THREAD

**Issue by zclongpop123** [AcademySoftwareFoundation/rez#1736]
Rez Version: >= 3.0
Command:  `rez-env houdini-20 -- houdini `

Rez will auto delete the temp rxt files, and when I use `rez-context --tools` in subprocess, command will faild, 
Command '['rez-context', '--tools']' returned non-zero exit status 1.

and I find the reason is rxt file is not exists,
So, how to keep rxt temp files in any way ?

**Comment by maxnbk** [comment]
This is for debugging, but perhaps this will do what you need.

https://rez.readthedocs.io/en/stable/environment.html#envvar-REZ_KEEP_TMPDIRS
