### ISSUE TITLE
Shell type plugin can resolve incorrectly in rez.system on Linux. 

### ISSUE THREAD

**Issue by cumulus-vfx** [AcademySoftwareFoundation/rez#1754]
This line in `rez.system.System.shell`
https://github.com/AcademySoftwareFoundation/rez/blob/a13f7bb362cbb05e73f88e9f771c36005c1e9f4a/src/rez/system.py#L91

Will throw a TypeError always as you cant replace with str char's on a byte string

So this function will always fallback to use $SHELL first to wrangle the shell name

This can be inaccurate in a case where the SHELL env var is wrong for the current running parent shell of the rez process
Where as if getting via ps is more reliable.

**Environment**
* Centos 7
* Rez version 2.112.0
* Rez python version 3.7

Issue still in latest release 3.1.1

**Comment by parikshittiwari740** [comment]
Hey @JeanChristopheMorinPerso, I have a PR out for this linked to the ticket 😄 

Sorry for tagging but I was not sure how/when the review is done and whether I am expected to do something after posting the PR. Please ignore my message if you guys are busy and I simply have to wait. Thansk!
