### ISSUE TITLE
Unrecognised package repository plugin: 'memory'

### ISSUE THREAD

**Issue by joeyskeys** [AcademySoftwareFoundation/rez#1771]
I was trying to reinstall rez after a system update which updated python. When I was doing "rez-bind platform", the error showed up "RezPluginError: Unrecognised package repository plugin: 'memory'"

**Environment**
* OS (linux Manjaro 24.0.1)
* Rez version (repository main)
* Rez python version (3.12.3)

**To Reproduce**
1. install rez;
2. run 'rez-bind platform'

**Expected behavior**
Everything goes fine, rez successfully bind platform package.

**Actual behavior**
It's reporting a error "RezPluginError: Unrecognised package repository plugin: 'memory'"

**Comment by JeanChristopheMorinPerso** [comment]
Rez is not compatible with python 3.12. see https://rez.readthedocs.io/en/stable/installation.html.
