### ISSUE TITLE
Backslash in rezconfig.py causing errors on fresh windows installations.

### ISSUE THREAD

**Issue by gregmcutlet** [AcademySoftwareFoundation/rez#1779]
Using Rez on Windows, I find that I have to manually remove a backslash in a comment in rezconfig.py before commands like rez-env will work

**Environment**
* OS Windows11
* Rez version 3.1.1
* Rez python version (output of "rez-python --version")

**To Reproduce**
1. run python3 install.py [install path]
2. run rez-env

**Expected behavior**
the command finishes, even --help

**Actual behavior**
a back slash in a comment causes the program to fail

**Comment by JeanChristopheMorinPerso** [comment]
Are you using python 3.12? If so, rez is not yet compatible with it.
