### ISSUE TITLE
When I run rez-env, I get an error of  "no shells available"

### ISSUE THREAD

**Issue by lingyunfx** [AcademySoftwareFoundation/rez#1807]
Describe the bug here.

**Environment**
* OS:：Windows 11
* Rez version：3.1.1
* Rez python version： 3.12.4

When I run "rez-env {package_name}", it triggers the error

![image](https://github.com/user-attachments/assets/4a99de0f-53b3-4298-8e39-eef58f826f4e)

when I run "rez-bind --quickstart"

![image](https://github.com/user-attachments/assets/e8763813-de7f-46e2-9783-3b8b19cb12a2)

Does anyone know what the reason is?

**Comment by lingyunfx** [comment]
Sorry, I didn't see that it doesn't seem to be compatible with python 3.12

**Comment by touraill-adobe** [comment]
I came here after stumbling on the same issue after a Fedora upgrade; I'm not sure why you closed the issue @lingyunfx: doesn't it make sense to track the compatibility issues with Python versions (maybe as a feature request rather than a bug)?
