### ISSUE TITLE
Set up a project security policy

### ISSUE THREAD

**Issue by cary-ilm** [AcademySoftwareFoundation/rez#1817]
Copy [SECURITY.md](https://github.com/AcademySoftwareFoundation/openexr/blob/main/SECURITY.md) from OpenEXR or one of the other ASWF projects, keep whatever's relevant and delete whatever doesn't apply to your project. This covers several of the OpenSSF badge requirements, like the policy and expectations.

Other ASWF projects support a security@<project>.org that forwards to your technical steering committee, but this is somewhat redundant with GitHub's private vulnerability reporting, which you've already configured.

**Comment by JeanChristopheMorinPerso** [comment]
Duplicate of #1650
