### ISSUE TITLE
Remove/replace all deprecated (python 2) magic methods (`__<method>__`)

### ISSUE THREAD

**Issue by JeanChristopheMorinPerso** [AcademySoftwareFoundation/rez#1833]
Relates to https://github.com/AcademySoftwareFoundation/rez/issues/1635

**Comment by lbreede** [comment]
@JeanChristopheMorinPerso are there any examples for deprecated dunder methods? I looked for `__cmp__`, `__nonzero__`, `__unicode__`, `__long__`, `__coerce__` but no hits

**Comment by lbreede** [comment]
@JeanChristopheMorinPerso 
The only mentions of `__cmp__`, `__nonzero__`, `__unicode__` are in the vendor directory.
The methods `__long__`, `__coerce__` are not present.

**Comment by JeanChristopheMorinPerso** [comment]
Thanks for taking a look @lbreede ! Would you mind commenting that in the linked issue please?

**Comment by JeanChristopheMorinPerso** [comment]
Oh wait, that's the issue. Nvm

**Comment by lbreede** [comment]
@JeanChristopheMorinPerso Let me know if there is anything else I can do for this issue, otherwise, we can close it.
