### ISSUE TITLE
Bound rez package fails to import under Python 2.7

### ISSUE THREAD

**Issue by captainhammy** [AcademySoftwareFoundation/rez#1844]
Greetings,

I am aware that Rez 3.x is Python 3 only, however I've come across an unexpected behavior when attemping to run tools under a resolved Python 2.7 environment. 

We have a variety of DCC versions on the go, some of which require Python 2.7 and the use of the rez module. In investigating moving from rez 2.x -> 3.x,  the bound rez package (generated via `rez-bind rez`) defines its requires as `requires = ['python-2.7+<4']`, however attempting to `import rez` under Python 2.7 results in a SyntaxError due to a print() statement:

```
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import rez
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "{package location}\rez\3.1.1\platform-windows\arch-AMD64\os-windows-10.0.19045.SP0\rez\__init__.py", line 43, in <module>
    _init_logging()
  File "{package location}\rez\3.1.1\platform-windows\arch-AMD64\os-windows-10.0.19045.SP0\rez\__init__.py", line 29, in _init_logging
    from rez.utils.colorize import ColorizedStreamHandler
  File "{package location}\rez\3.1.1\platform-windows\arch-AMD64\os-windows-10.0.19045.SP0\rez\utils\colorize.py", line 326
    print(self.get(msg, style), file=self.buf)
                                    ^
SyntaxError: invalid syntax
```
Given that Rez 3.x is supposed to be Python 3 only, I would assume that the requirement range should in fact be '3+<4' such that a 2.x version of Rez would be found when resolving with python-2.7 in the request. However if the API itself is still intended to be usable under Python 2.7 then it would be great if the code to be updated to not error.

Thanks

**Environment**
* OS: Windows 10
* Rez version: 3.1.1
* Rez python version: 3.11.7

**Comment by JeanChristopheMorinPerso** [comment]
Hi @captainhammy, thanks for reporting this. We completely forgot to change the requirement in the bound package. That's on us.

**Comment by JeanChristopheMorinPerso** [comment]
This will be fixed in the next release.

**Comment by captainhammy** [comment]
Thanks for the quick fix!
