### ISSUE TITLE
add message queue release hook

### ISSUE THREAD

**Issue by nerdvegas** [AcademySoftwareFoundation/rez#222]
Add an AMQP release hook for sending message on package release. Thinking of using Kombu atm, but whatever AMQP client is lightweight and pure python (the source will be embedded in rez as with its other dependencies).

**Comment by JeanChristopheMorinPerso** [comment]
This was added in https://github.com/AcademySoftwareFoundation/rez/pull/287, which is rez [2.0.rc1.39](https://github.com/AcademySoftwareFoundation/rez/releases/tag/2.0.rc1.39). That's quite a while ago :)
