### ISSUE TITLE
can not run rez-config and rez-run on windows

### ISSUE THREAD

**Issue by hongloull** [AcademySoftwareFoundation/rez#233]
If run "rez-config" on windows, I get below error message:
  File "d:\apps\rez\lib\site-packages\rez-2.0.rc1.25-py2.7.egg\rez\utils\platfor
m_.py", line 96, in _difftool
    raise NotImplementedError
NotImplementedError
Do we have a plan to support run "rez-config" and "rez-run" on windows or I didn't install rez correctly?

**Comment by nerdvegas** [comment]
Hey hongloull,

There's just a little code not implemented yet, which defines a default
diffing tool on Windows. I'll set some hopefully sensible default, which
will remove this error.

In the meantime, just try setting the environment variable REZ_DIFFTOOL,
and try again. This might remove the error. If it doesn't you just need to
update the code to add the _difftool() function to class WindowsPlatform,
in utils/platform_.py.

Thx
A

**Comment by mstreatfield** [comment]
There is a fix for this included in #204.

**Comment by nerdvegas** [comment]
Aha! Which I will get to soon. Thx Mark,
A

**Comment by JeanChristopheMorinPerso** [comment]
There is no command called `rez-run` nowadays, so I'll close this.
