### ISSUE TITLE
add package attribute injection config entry

### ISSUE THREAD

**Issue by nerdvegas** [AcademySoftwareFoundation/rez#297]
There should be a config entry that adds attribute(s) to a package on release.

Use case: We have multiple studio locations that all release packages, and for multiple reasons we need to know where a package was released from. Grafting a "location" attribute onto each package release would give us this.

**Comment by JeanChristopheMorinPerso** [comment]
This can be achieved using [package_preprocess_function](https://github.com/AcademySoftwareFoundation/rez/wiki/Configuring-Rez#package_preprocess_function) in a studio's config.
