### ISSUE TITLE
UnixPlatform distribution inconsistent

### ISSUE THREAD

**Issue by bfloch** [AcademySoftwareFoundation/rez#309]
The way that the linux distribution/os is determined in rez is currently
1. parse /etc/lsb-release 
2. try getting the output of the lsb_release program
3. use python's dist detection

The  3. is indeed unreliable and is about to become deprecated and removed in python 3.6
http://bugs.python.org/issue1322 (which we do not care about for the time being at python2.7)

However we have an case where Scientific Linux machines are evaluated either as
"Scientific" based on 2. if a machine has redhat-lsb-core installed, or "Scientific Linux" if not and it falls back to 3. (which ends up using /etc/redhat-release as far as I can tell). The difference lies in the implementation of lsb_release (a monster bash script) vs. platform.py from python.

Linux won't give us a satisfying result however we do care about consistency.
We can hack around it but ultimately I would love to see a solution that ends up in rez and at least gives us the expected results.

Following suggestions:
1. Make Platform_.os() a plugin so the maintainer is in control
2. Allow for os aliases within the rezconfig. Scientific would map to Scientific Linux as long as the versions match.
3. Allow to configure the order of fallbacks

Personally I'd prefer the 2nd solution as it would solve our issue. However it will not solve the issue for someone that gets debian reported from an ubuntu system.

Opinions?

**Comment by nerdvegas** [comment]
Option 2 strikes me as the simplest solution. Option 1 feels like overkill,
and 3 may not fix all cases, but I think there's a good chance 2 will work
for everyone.

A

**Comment by JeanChristopheMorinPerso** [comment]
I'll take a guess and consider this as solved since it's 6 years old and we now use the `distro` library which should be more reliable.
