### ISSUE TITLE
Home directory doesn't expand on Windows with default config

### ISSUE THREAD

**Issue by assumptionsoup** [AcademySoftwareFoundation/rez#313]
I'm using git-bash on windows with the master branch.  I suspect this is a problem with cmd.exe too.

```
>~$ rez-bind platform
rez: PackageRepositoryError: Lockfile directory C:\Users\jordan\~\packages does not exist - please create and try again
```

On my system, `~/packages` does exist.  What does not exist is `~/~/packages`.
I've tracked down the error to here https://github.com/nerdvegas/rez/blob/master/src/rez/utils/formatting.py#L460
The relevant part is:

```
        i = path.find(os.path.sep, 1)
        if i < 0:
            i = len(path)
        if i != 1:
            return path
```

The problem is that in git-bash, `os.path.sep` is `\\` (as with all nt systems), but the default config specifies `~/packages`.  Thus `~/packages` is not expanded.  In order for rez to work out of the box, I think this section of code should be changed to obey `os.path.sep` and `/`.  Or perhaps the default config should differ across platforms (such that nt systems default to `~\\packages`).  What are your thoughts?

As a side note, `os.path.expanduser('~/packages')` works correctly in this scenario.  It's just the custom expanduser implementation in rez that does not.

**Update:** `"${HOME}/packages"` works on windows and posix since it uses variable expansion instead of user expansion.  Using an explicit `$HOME` variable in the default rezconfig.py instead of `~` could solve this issue.

**Comment by mvtk** [comment]
:+1:  for more sensible platform specific defaults. Though i am not sure if the implementation could maybe be done a little bit different that makes shure weak references are not destroyed but not drop using expanduser entirely on NT but use it selectively instead.

**Comment by nerdvegas** [comment]
Does anyone see a problem with updating rezconfig.py to do like so:

local_packages_path = os.path.join("~", "packages")

? That should fix the issue I think.
A

**Comment by JeanChristopheMorinPerso** [comment]
Seems to be fixed by https://github.com/AcademySoftwareFoundation/rez/pull/319
