### ISSUE TITLE
Windows CMD plugin recording system paths in wrong order

### ISSUE THREAD

**Issue by yawpitch** [AcademySoftwareFoundation/rez#344]
The existing **rezplugins/shell/cmd.py** has a classmethod _CMD.get_syspaths_ which is currently scrambling the order of the system paths returned from an inspection of the Windows registry.

The cause is this line:

```
cls.syspaths = set([x for x in paths if x])
```

The cast to a set eliminates duplicate items, but since a set is inherently unordered it also loses the original sort order, which can be very relevant in a shell search. Additionally this only happens in the Windows plugin, all others return in their original order and without duplication removal.

Working on a fix that will still do a quick removal of duplicates but will preserve order.

**Comment by michaelmovies** [comment]
Fixed in #341.

**Comment by bsilvaLS** [comment]
This issue cropped up for me this week, as the cmd and powershell plug-ins in the master branch are still using a set(), and scrambling the path on Windows. Any chance we can get this commit wrapped into master?

https://github.com/Pixomondo/rez/commit/ae10c1580f66ae11d9d11ef1392b2a9b8b33e9ac

**Comment by nerdvegas** [comment]
I'll take a look at this soon.
Thx
A

**Comment by JeanChristopheMorinPerso** [comment]
This is fixed now AFAIK.
