### ISSUE TITLE
setting alias with package.py

### ISSUE THREAD

**Issue by antipyretiquel** [AcademySoftwareFoundation/rez#346]
I have a package.py file like so:

config_version = '0'

uuid = '4f4dd5f5-54ce-4d84-8438-018920ea1707'

name = 'krita'

version = '3.0.99.91'

description = 'Krita Desktop is a free an open source painting application.'

help = [[ "User Documentation", "$BROWSER https://docs.krita.org/Main_Page" ]]

external = 'true'

authors = [ 'Krita Foundation' ]

private_build_requires = ['cmake']

requires = ['python-2.7']

variants = [[ 'CentOS-6.2+<7' ]]

def commands():
    import os
    prependenv('CMAKE_MODULE_PATH', '{root}/cmake')
    env.KRITA_EXE = '{root}/bin/krita-${REZ_KRITA_VERSION}-Beta-x86_64.appimage'

def post_commands():
    import os
    userdir = "{0}/.local/share/appimagekit/".format(os.path.expanduser('~'))
    userfile = "{0}no_desktopintegration".format(userdir)
    if not os.path.isdir(userdir):
        os.makedirs(userdir, 0777)
    if not os.path.isfile(userfile):
        with open(userfile, 'w') as f:
            f.write('')

custom = {'use_chroot': True}

and this builds and deploys fine... however I would like to be able to set an alias for the appimage... how would you do this from a package.py and is there any documentation on this?

**Comment by instinct-vfx** [comment]
There is an alias command for use in commands(). You can find information on this and all other commands here: https://github.com/nerdvegas/rez/wiki/Package-Commands#alias
