### ISSUE TITLE
~/.rezconfig is parsed as yaml even though it contains python

### ISSUE THREAD

**Issue by ttanimura** [AcademySoftwareFoundation/rez#367]
I copied the contents of the default `rezconfig.py` into `~/.rezconfig` as a test, but when I try to build anything I get a `ConfigurationError`. Scanning the code, it appears its because only files with a .py extension are mapped to the Python loader. Everything else is treated as yaml (see `_load_config_from_filepaths` in `config.py`)

I wonder if it would be better to try loading it as Python first, and if an exception is thrown, fall back to yaml instead? That way the configs can be extension agnostic and work more robustly.

**Comment by gst** [comment]
Hi,

you only have to name your file _~/.rezconfig_**.py** and it should load properly.

regards,

Greg.
