### ISSUE TITLE
Installation failing on macOs.

### ISSUE THREAD

**Issue by KelSolaar** [AcademySoftwareFoundation/rez#387]
Hi,

I'm having some issues installing the package on macOs:

```bash
Kali:rez kelsolaar$ python install.py -v /Users/kelsolaar/.rez

installing rez to /Users/kelsolaar/.rez...
/Users/kelsolaar/.rez/bin/python
-c
import sys, pip; sys.exit(pip.main(["install", "--ignore-installed"] + sys.argv[1:]))
setuptools
pip
Traceback (most recent call last):
  File "install.py", line 133, in <module>
    create_environment(dest_dir)
  File "/Users/kelsolaar/Documents/Development/ThirdParty/rez/src/build_utils/virtualenv/virtualenv.py", line 993, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/Users/kelsolaar/Documents/Development/ThirdParty/rez/src/build_utils/virtualenv/virtualenv.py", line 961, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/Users/kelsolaar/Documents/Development/ThirdParty/rez/src/build_utils/virtualenv/virtualenv.py", line 903, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/kelsolaar/.rez/bin/python -c "import sys, pip; sys.exit(pip.main([\"install\", \"--ignore-installed\"] + sys.argv[1:]))" setuptools pip failed with error code 1
```

While investigating I noticed that the output traceback from the sub-process is eaten, which is confirmed by printing `all_output` (`print('\n'.join(all_output))`) after that line here: https://github.com/nerdvegas/rez/blob/master/src/build_utils/virtualenv/virtualenv.py#L894

```bash
Kali:rez kelsolaar$ python install.py -v /Users/kelsolaar/.rez
installing rez to /Users/kelsolaar/.rez...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/kelsolaar/Documents/Development/ThirdParty/rez/src/build_utils/virtualenv/virtualenv_support/pip-1.5.6-py2.py3-none-any.whl/pip/__init__.py", line 9, in <module>
  File "/Users/kelsolaar/Documents/Development/ThirdParty/rez/src/build_utils/virtualenv/virtualenv_support/pip-1.5.6-py2.py3-none-any.whl/pip/log.py", line 8, in <module>
  File "/Users/kelsolaar/Documents/Development/ThirdParty/rez/src/build_utils/virtualenv/virtualenv_support/pip-1.5.6-py2.py3-none-any.whl/pip/backwardcompat/__init__.py", line 66, in <module>
  File "//anaconda/lib/python2.7/urllib2.py", line 94, in <module>
    import httplib
  File "//anaconda/lib/python2.7/httplib.py", line 80, in <module>
    import mimetools
  File "//anaconda/lib/python2.7/mimetools.py", line 6, in <module>
    import tempfile
  File "//anaconda/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "//anaconda/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/Users/kelsolaar/.rez/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /Users/kelsolaar/.rez/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /Users/kelsolaar/.rez/lib/python2.7/lib-dynload/_io.so
Traceback (most recent call last):
  File "install.py", line 133, in <module>
    create_environment(dest_dir)
  File "/Users/kelsolaar/Documents/Development/ThirdParty/rez/src/build_utils/virtualenv/virtualenv.py", line 993, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/Users/kelsolaar/Documents/Development/ThirdParty/rez/src/build_utils/virtualenv/virtualenv.py", line 961, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/Users/kelsolaar/Documents/Development/ThirdParty/rez/src/build_utils/virtualenv/virtualenv.py", line 903, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/kelsolaar/.rez/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 1
```

I would suggest printing the output in the final raised exception.

Now coming back to my issue, I'm using multiples Python interpreters (System, Homebrew, Anaconda), my main one being the Anaconda one, however I noticed that the virtualenv you create for *rez* is using macOs shipped Python which is incompatible with the Anaconda one, any direct way to specify the interpreter to use?

**Comment by KelSolaar** [comment]
Actually the question on being able to specify the interpreter *rez* uses is also valid on Windows.

**Comment by nerdvegas** [comment]
Hey Thomas,

The python interpreter used in the rez install *should* have no bearing on
the python interpreter used anywhere else (including packages into rez
packages). Are you seeing otherwise? To control the python interpreter that
the install uses, just use a specific python interpreter when running
install.py, that should be the one that gets copied(?) into the
virtualenv-based installation.

Thx
A

**Comment by KelSolaar** [comment]
@nerdvegas, Allan: Given my system, *rez* is not picking the proper python interpreter, which should be the Anaconda one:

```bash
Kali:~ kelsolaar$ which -a python
/anaconda/bin/python
/usr/local/bin/python
/usr/bin/python
```

This is my default python and the one used for a vanilla shelf:
```bash
Kali:bin kelsolaar$ python
Python 2.7.11 |Anaconda custom (x86_64)| (default, Jun 15 2016, 16:09:16) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>>
```

and this is the binary picked by *rez* on installation:

```bash
Kali:bin kelsolaar$ pwd
/Users/kelsolaar/Applications/rez/bin
Kali:bin kelsolaar$ ./python
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

I can likely submit a PR for the proper exception traceback too as it is quite critical to me to understand what is going on under the hood, need to check with upstream hierarchy before though :)

Cheers,

Thomas

**Comment by nerdvegas** [comment]
Ack, if the installation is using a different interpreter to the one you
used on install.py, the issue is likely somewhere in virtualenv :/.

The installation process (under the hood, not for the user) is painful to
say the least. I've started to think that perhaps we could direct efforts
into platform-specific, simpler installers. For example I'm pretty sure I
can implement a much simpler linux-specific installation that doesn't use
virtualenv (and I'm pretty sure there's a small performance gain that way
too). That's been on my list for a while.

A

**Comment by KelSolaar** [comment]
> The installation process (under the hood, not for the user) is painful to
say the least.

Yeah I saw a lot of magic happening there :) Another related issue was Qt for *rez-gui*, I had to manually copy the needed packages to the *rez* virtual environment as it wasn't picking the one from my interpreter. I reckon that platform specific installers would be useful in the long term, especially from a provisioning / orchestration stand point, it would make deployment easy.

By the way I hope you don't mind the multiple issues I raised lately, if it can comfort you, even with its quirks I'm very happy with the tool so far and it is hopefully the solution we will adopt. Side question, do you have a Slack, Gitter, IRC, your_preferred_chat_client team for *rez* somewhere?

**Comment by melMass** [comment]
@KelSolaar did you managed to find a workaround? I basically have the same setup as yours. OSX and Conda

**Comment by JeanChristopheMorinPerso** [comment]
This issue is quite old. I'll consider it "fixed".
