### ISSUE TITLE
Error evaluating yaml packages

### ISSUE THREAD

**Issue by pmolodo** [AcademySoftwareFoundation/rez#393]
I know package.yaml files are discouraged, but... our studio still has a bunch of them, and I haven't had a chance to go through and batch convert everything to .py yet (particularly since I don't want to lose comments, etc).

Anyway - if a package.yaml has code like this:

```
commands: 
    rr = 'test'
    env.RR = '{rr}'
```

...then it will currently error.  Looks like you've already got some code to handle this situation for .py files (you may recognize the example - I pulled it from `process_python_objects()` in `serialise.py`), but no such consideration for yaml files.

For our internal use, I set the default for `eval_as_function` to False, in `sourcecode.SourceCode.__init__()`.  Not sure if this is the best way to handle this, or what other impacts it may have, though, so I didn't bother submitting it as a pull request. Seems to work for us for now, though...

**Comment by nerdvegas** [comment]
Hey Paul,

Ah yes I see. I'll test that and patch up whatever breaks, will let you
know once merged.

Note though that the @early/@late stuff won't work in yaml files I'm pretty
sure. I need to formalize the fact that yaml is basically deprecated. But
yes, they should still work to the extent that they already were.

Cheers
A

**Comment by elrond79** [comment]
Yeah, there's no point adding @early / @late support to yaml files. Good
way to encourage people to migrate to .py, too, if they haven't already...
it's a nice new feature.

**Comment by JeanChristopheMorinPerso** [comment]
I'll close this one. YAML package definitions are used anymore...
