### ISSUE TITLE
Python API apply() doesn't work

### ISSUE THREAD

**Issue by Kaiserlicht** [AcademySoftwareFoundation/rez#438]
Windows 10 x64, Rez 2.13.0

in mypackage I have
def commands():
    env.MYENV='foo'

In a python shell the following fails because apply() apparently doesn't set the environment. 
from rez.resolved_context import ResolvedContext
r = ResolvedContext(['mypackage '])
r.apply()
import os
print os.environ['MYENV']

**Comment by fnaum** [comment]
found a fix. just one line
I'll create a PR

**Comment by JeanChristopheMorinPerso** [comment]
Fixed in #440
