### ISSUE TITLE
VersionRange breaks if range is not in order

### ISSUE THREAD

**Issue by instinct-vfx** [AcademySoftwareFoundation/rez#455]
I am not 100% sure this is a bug or may be expected and/or wanted. As mentioned before i have my own incarnation of rez-pip mostly for windows versions. It fails when installing requests with dependencies because the urllib3 requirement is stated in "inverse" order.
I am unsure where this comes from. It seems fine in the setup.py of requests but it is inverted on pypi already so it is not being interpreted wrong within rez or distlib.

Anyways it is easy to reproduce:

```
from rez.vendor.version.version import VersionRange
print VersionRange('>=1.21.1,<1.23')
print VersionRange('<1.23,>=1.21.1')
```

The first one works the second breaks with a Syntax Error:

`PackageRequest(u'urllib3-<1.23,>=1.21.1') raised VersionError(u"Syntax error in version range '<1.23,>=1.21.1': Syntax error in version range '<1.23,>=1.21.1'",)`

**Comment by instinct-vfx** [comment]
Taking a closer look this is "as designed" but i am not sure if it is intended. It is also _VersionRangeParser breaking of course. I guess my question is if i have to sanitize versions before passing them to _VersionRangeParser or create a PR that adds support for flipped range bounds to version_range_regex

**Comment by nerdvegas** [comment]
If this is reporting as a sytax error then I'd consider it a bug.

It's been ages since I touched that code so I don't recall how it's being
implemented, but I'd say that if commas are present then it'd be reasonable
to treat them as an AND - ie, create ranges for each comma-separated token,
then union them.

**Comment by instinct-vfx** [comment]
I just took a look and essentially it is a huge regex that does expect lower_bound,upper_bound only. I will take a look but i suck with regexes so i am not sure if i can get that to work. It seems to affect quite a few packages here now though and i wonder if anything on the pip / pypi side has changed? I don't remember that happening before.

**Comment by nerdvegas** [comment]
Mmm, I'll have to take a look.

A


On Tue, Sep 12, 2017 at 5:56 PM, Thorsten Kaufmann <notifications@github.com

**Comment by instinct-vfx** [comment]
A colleague of mine @PatrickFoerster extended the regex in version.py to support both ascending and descending order. With the cases i had this works fine. Here is the MR: #470

**Comment by JeanChristopheMorinPerso** [comment]
Fixed by https://github.com/AcademySoftwareFoundation/rez/pull/618
