### ISSUE TITLE
Suggestion: Use distro instead of platform for linux_distribution()

### ISSUE THREAD

**Issue by oktomus** [AcademySoftwareFoundation/rez#516]
`platform.linux_distribution()` will be removed in python 3.8 and it fails to detect some systems.

**Comment by skral** [comment]
I think that's a good idea because [distro](https://github.com/nir0s/distro) is quite versatile and why would we want to maintain our own version of it when there is something readily available that is tested and works.

**Comment by nerdvegas** [comment]
+1

A

**Comment by bfloch** [comment]
Having a more standard way would definitely be appreciated.
For example: we noticed that currently having redhat's lsb or not does influence the result a lot.

For any changes during a transition we have:
https://github.com/nerdvegas/rez/wiki/Configuring-Rez#platform_map
So it should be safe as long as it is advertised.
