### ISSUE TITLE
Centos7 /etc/profile.d

### ISSUE THREAD

**Issue by plboily** [AcademySoftwareFoundation/rez#527]
Hi,
  I am using cenos7. If i have a bash script in /etc/profile.d let say call maya.sh with this in it:
export MAYA_MODULE_PATH=/opt/Golaem/Golaem-6-Maya2017
And with rez i have a package call maya with this as a command:
def commands():
    env.MAYA_PLUGIN_PATH.append("/dir1/dir2")
    env.MAYA_MODULE_PATH.append("/dir1/dir2")

Then i am doing this:
rez-env maya

MAYA_PLUGIN_PATH will be correctly set but MAYA_MODULE_PATH will not append the new path. It will only stay to the maya.sh setup.

**Comment by nerdvegas** [comment]
Are you expecting MAYA_MODULE_PATH to be set to `/opt/Golaem/
Golaem-6-Maya2017:/dir1/dir2`?

If so, read here:
https://github.com/nerdvegas/rez/wiki/Package-Commands#variable-appending-and-prepending

Your packages should probably be organised differently. That is to say,
Golaem should be a package that requires maya, and you would `rez-env
Golaem-6` instead. However I also realise that you may be in a partially
migrated state and Golaem may not be available as a rez package yet.

The way that rez handles env vars can and should be improved, but I've not
started work on this yet. Ideally it would be able to keep pre-rez-env
path-like vars intact, and keep that value appended to the modified var
within resolved environments.

Hth
A

**Comment by blake-sweeney** [comment]
Everything in /etc/profile.d is sourced in a subshell, and a rez-env resolves the package variables and then resources everything in /etc/profile.d within the resulting subshell.

Like Allan said, best solution is to move Golaem environment variables into a package.  If that’s not an option, you can update maya.sh to only set the env var if it doesn’t already exist.

**Comment by plboily** [comment]
Hi,
   it was not very specific to Golaem, it was more about the "concept" of variable existing in a sh file into /etc/profile.d can not be set with a rez-env. But i totally understand what you are saying and i will genlty remove all the necessary .sh file into rez.

thanks a lot.
