### ISSUE TITLE
rez-env with python -c. One command line erroring

### ISSUE THREAD

**Issue by ISkipy** [AcademySoftwareFoundation/rez#538]
Hey guys,

In a command prompt on Windows7 with python 2.7.12.

`rez-env python-2.7.12 arcade_prodigy -- python -c "exec(\"import arcade_prodigy\")"`
Does not work: see screen shot below.
![image](https://user-images.githubusercontent.com/35566104/47783930-021b1a00-dcfc-11e8-99f9-bfb01f95881c.png)

When entering in the rez-env and then calling the python command works:
`rez-env python-2.7.12 arcade_prodigy`
`> python -c "exec(\"import arcade_prodigy\")"`

This is the most simple example I could made to replicate the issue.
Maybe because the `-c` flag exists in `rez-env` itself?

Thanks,
Clement

**Comment by davidlatwe** [comment]
I can confirm that either
```
> rez-env python -- python -c "print('hello')"
hello
```
or
```
> rez-env python -- python -c "print(\"hello\")"
hello
```
both works on Windows with latest Rez (2.66.0).
