### ISSUE TITLE
Incompatible windows-os package between local job and cloud render

### ISSUE THREAD

**Issue by wizofe** [AcademySoftwareFoundation/rez#575]
When I generate a job from [deadline](https://deadline.thinkboxsoftware.com/) that renders on the cloud, I get the `os-windows-xxx package` is incompatible. There's a different version of Windows running in the Cloud and a different one locally (Server vs 7).

The version of `rez` currently running is the 2.0 (I know it isn't the latest but there are a lot of systems to upgrade). The weird thing is that the job is running when executed locally but not when sent to the cloud. Could that be an `os` variant definition in some `package.py`? Or the issue that is fixed by version [2.26.0](https://github.com/nerdvegas/rez/releases/tag/2.26.0)?

Thanks!

**Comment by instinct-vfx** [comment]
You can use the platform-map configuration option to map versions to be less specific:
https://github.com/nerdvegas/rez/wiki/Configuring-Rez#platform_map

Does that maybe help?

**Comment by wizofe** [comment]
Didn't really help. Getting still ... intersected with range ... resulted in no packages.

**Comment by nerdvegas** [comment]
Hi,

There isn't enough info to go on really. What is the error you get
specifically? By 'incompatible' do you mean that you get a resolve conflict?

If so, you could try simply manually setting REZ_IMPLICIT_PACKAGES to
include the windows OS variant present on cloud, and do a resolve locally.
If that fails then there must be some package with a requirement on
windows-7.

I'm not sure what potentially-fixed issue you're referring to?

Thx
A

**Comment by wizofe** [comment]
Ok. Here's a log [LOG](https://paste.ofcode.org/373tZVZEmHFPi66HGXQN7ZX) if I try to create a `rez env` on the cloud.

The issue is that when I submit a job from the local deadline manager to the cloud I can't resolve the environment and the job fails. Note: the packages are read from a central server location if that matters.

Here's [LOG1](https://paste.ofcode.org/KfPPut5i6jdrVExY2CMT2Q) and I am going to attach the LOG2 when I have it (that shows the message of intersected packages instead).
