### ISSUE TITLE
Rez System.os is returning a distname that causes errors

### ISSUE THREAD

**Issue by Ahuge** [AcademySoftwareFoundation/rez#684]
On linux, rez.system.os calls `platform.linux_distribution()` which on my installation of CentOS returns `('CentOS Linux', '7.6.1810', 'Core')`

The problem appears to be the space in the `CentOS Linux`.

I get the following traceback:
```python
Traceback (most recent call last):
  File "/tmp/rezvenv/bin/rez-bind", line 11, in <module>
    run("bind")
  File "/tmp/rezvenv/lib/python2.7/site-packages/rez/cli/_main.py", line 227, in run
    returncode = opts.func(opts, opts.parser)
  File "/tmp/rezvenv/lib/python2.7/site-packages/rez/cli/bind.py", line 109, in command
    parser=bind_parser)
  File "/tmp/rezvenv/lib/python2.7/site-packages/rez/bind/python.py", line 39, in bind
    pkg.add_variant(*system.variant)
  File "/tmp/rezvenv/lib/python2.7/site-packages/rez/package_maker_.py", line 169, in add_variant
    self.variants.append([Requirement(x) for x in requires])
  File "/tmp/rezvenv/lib/python2.7/site-packages/rez/vendor/version/requirement.py", line 127, in __init__
    self.range_ = VersionRange(req_str)
  File "/tmp/rezvenv/lib/python2.7/site-packages/rez/vendor/version/version.py", line 614, in __init__
    % (range_str, str(e)))
rez.vendor.version.util.VersionError: Syntax error in version range 'CentOS Linux-7.6.1810': Expected end of text (at char 7), (line:1, col:8)
```

It appears that the `System._make_safe_version` on line 111 of rez/system.py does not actually make it safe.

platform.linux_distributionn is now deprecated in Python 3.5 and removed in 3.8
https://docs.python.org/2/library/platform.html

They are pointing us to https://github.com/nir0s/distro

When I switched to that for my self, I was no longer having issues.

Has anyone else come across this? Perhaps I am making wildy incorrect assumptions but I haven't had a chance to use rez yet as this issue happened right as I started using it.

**Comment by Ahuge** [comment]
Rez version 2.0.ALPHA.52
Platform Linux CentOS 7.6.1810

The command I was running was `rez-bind python`

**Comment by JeanChristopheMorinPerso** [comment]
Hi @Ahuge, could you try with the latest version of rez (2.38.2)? `2.0.ALPHA.52` is quite old. You can try with the version in the master branch, which is the latest stable release.

I am currently using CentOS 7.6.1810 like you and I don't have this issue.

See:
```python
>>> rez.__version__
'2.23.1'
>>> rez.system.system.variant
['platform-linux', 'arch-x86_64', 'os-CentOS-7.6.1810']
```

Let me know how it goes.

**Comment by Ahuge** [comment]
Will do, I'll try tomorrow

**Comment by nerdvegas** [comment]
The 'distro' lib has been mentioned before, and it sounds like it's
probably the way to go. Let's keep in mind as a separate PR, especially as
it may give more py3 compatibility.

Cheers
A

**Comment by JeanChristopheMorinPerso** [comment]
We now use the `distro` lib. Closing this.
