### ISSUE TITLE
Alias can't be used on the same line as rez-env

### ISSUE THREAD

**Issue by JanRiebeAxis** [AcademySoftwareFoundation/rez#708]
We are observing some unexpected behaviour with the alias feature.

For the examples let's assume we are setting up a package 'alias_test' in which we define alias('alias_command', 'echo alias successfully excecuted')

When entering a rez shell that includes a package which sets an alias the alias can afterwards be used as expected.
Example:
C:\Users\me>rez-env alias_test
> C:\Users\me>alias_command
> C:\Users\me>alias successfully executed

However when running the alias command in the same line the alias is not recognised.
Example:
C:\Users\me>rez-env alias_test -- alias_command
> C:\Users\me>'alias_command' is not recognized as an internal or external command,
operable program or batch file.

This was mentioned before in issue #389 but appears to still occur.

**Comment by instinct-vfx** [comment]
This is currently expected because if you use the command syntax with -- (or -c) there is no actual shell created and hence doskey is never run. This works with the powershell and pwsh plugins. I am actually not sure if there is a really good way to support this.

**Comment by JanRiebeAxis** [comment]
Thanks for the insight. That makes sense, though it would be a good feature to have.
As a workaround we are now considering to wrap commands into batch scripts, to act as an alias would, and append these to path in the rez package.

**Comment by JeanChristopheMorinPerso** [comment]
Fixed by #948
