### ISSUE TITLE
Improvements on Windows Tests

### ISSUE THREAD

**Issue by bfloch** [AcademySoftwareFoundation/rez#789]
- [x] Rename workflow name from `Windows Docker` to `Windows`
- [x] Rename `Run the docker image` step to `Run rez selftests` or similar
- [x] Fix PR builds
  - [x] Checkout right state of PR #800
  - [x] Run image without docker token #795 
- [x] Cleanup old images on docker hub
  - Could be a `on: schedules` action
- [x] Better error handling when image is not available yet
  - [x] Explore option to use single merged workflow / `:latest` only image
- [x] Explore option to use Github Registry
  - Currently blocked by: https://github.community/t5/GitHub-Actions/Docker-Push-to-Package-Registry-from-Windows/m-p/36393
  - Does not allow deletion on public repos :-/
- [x] Try to find workaround to utilize base github image without docker
  - https://github.community/t5/GitHub-Actions/Windows-image-bloat-in-PATH-disables-cmd-prompt-usage/m-p/36004#M2414

**Comment by nerdvegas** [comment]
Since they're trivial, I will address the first 2 points at the same time I merge #786. 

Wrt the rest, they come with the caveat that Github Package Registry could become an option instead, at which point some or all of these issues may be moot. We'll have to wait and see.

**Comment by bfloch** [comment]
One way to deal with these failures is to always tag `:latest` images.
So as a fallback for the `windows` workflow, if no uniquely tagged image is available fallback to `:latest`.
I think @nerdvegas suggested this in the chat yesterday.
I'll look into it.

**Comment by nerdvegas** [comment]
Yeah I'm finding the delay on image registration on dockerhub to be pretty frustrating. It's in the order of 5-10 minutes and I've often had a follow up windows CI run fail because of that.

**Comment by bfloch** [comment]
I posted all over the place already: You can rerun failed workflows after the image is build from the UI. You still have to wait for the image to be pushed though.

**Comment by JeanChristopheMorinPerso** [comment]
We did an overhaul of the windows tests last year. I'll close this issue as done for now.
