### ISSUE TITLE
rez-pip does not include platform/arch in generated variants for pure python packages with console_scripts

### ISSUE THREAD

**Issue by bpabel** [AcademySoftwareFoundation/rez#907]
When building a python package that contains console_script entry points, python build systems will generate an platform/arch-specific binary executable.

Because this executable is platform/arch-specific, the platform/arch should be included in the generated variant.  This will allow rez-pip to be run from multiple platform/arch's, each building different variants with different console_script executables.

**Comment by nerdvegas** [comment]
Do you know if this is also the case for linux? I'd have thought not as shebanged scripts are created in that case.

In any case, no work has been put into detecting platform-dependent packages as yet, but we can start, even if that's just getting set for packages with console entry points on Windows.

**Comment by JeanChristopheMorinPerso** [comment]
Fixed by #1287
